import { href } from '../router'
import { useLocale } from '../i18n'
import SaveResourceButton from './SaveResourceButton'

const phases = [
  { slug:'fase-00-orientacion-y-diagnostico', title:'Define tu punto de partida', goal:'Elegir una tarea útil y un objetivo que puedas comprobar.', concept:'Aprender una herramienta tiene sentido cuando sabes para qué la necesitas. Empieza por una tarea que ya conozcas: resumir notas, ordenar solicitudes o preparar una página informativa. Elige una sola. No necesitas saber programar para comenzar; sí necesitas poder reconocer un resultado correcto.', example:'Ana recibe notas de reuniones y tarda veinte minutos en convertirlas en tareas. Su objetivo inicial es obtener una tabla con tarea, responsable y fecha. Si la nota no indica una fecha, la tabla debe decir «No indicada». Todavía no enviará mensajes ni conectará cuentas.', steps:['Escribe qué tarea repites, quién utiliza el resultado y cómo la haces hoy.','Prepara una muestra ficticia de cinco a diez líneas. Conserva una solución hecha por ti para poder comparar.','Anota qué sabes hacer sin ayuda y qué necesitas aprender. Elige una herramienta del catálogo según la tarea.'], deliver:'Una ficha con tarea, muestra, resultado esperado y tiempo disponible para practicar.', criterion:'Puedes explicar en una frase qué vas a producir y señalar tres características que debe cumplir.', link:'herramientas', cta:'Elegir una herramienta' },
  { slug:'fase-01-aprendizaje', title:'Comprende y practica los fundamentos', goal:'Entender las decisiones que hay detrás de una instrucción y de su resultado.', concept:'Una instrucción explica qué quieres; el contexto aporta la información necesaria para hacerlo. La respuesta de una IA es una propuesta que debes revisar. Una respuesta bien escrita puede contener un dato inventado. Por eso aprenderás a separar lo que aparece en la fuente de lo que el sistema deduce o desconoce.', example:'La nota dice: «Ana prepara el presupuesto el martes. Luis lo revisa el jueves». Una tabla correcta tiene dos filas. No añade un importe ni transforma «martes» en una fecha de calendario sin conocer la semana. Esta comparación enseña a revisar información, no solo presentación.', steps:['Abre las primeras unidades de la herramienta elegida y lee el ejemplo resuelto antes de reproducirlo.','Realiza la práctica con los datos de muestra. Compara cada nombre, número y fecha con el original.','Modifica un dato de la muestra y vuelve a ejecutar. Explica qué cambió en el resultado y por qué.'], deliver:'La muestra original, la instrucción utilizada y el resultado corregido, con una explicación de los cambios.', criterion:'Puedes repetir el ejercicio y detectar al menos una afirmación que no está respaldada por la entrada.', link:'herramientas', cta:'Estudiar las unidades de una herramienta' },
  { slug:'fase-02-aplicacion-a-trabajo-e-ideas', title:'Aplica lo aprendido a una tarea completa', goal:'Convertir una práctica aislada en una forma de trabajar que puedas repetir.', concept:'Un procedimiento tiene una entrada, varios pasos y una salida. En esta fase realizas esos pasos de forma manual para entenderlos. No conviene automatizar un proceso que aún no sabes explicar: si los criterios cambian en cada intento, también cambiará lo que debería hacer una automatización.', example:'Ana define su procedimiento: copiar una nota autorizada, extraer tareas, contrastar responsables y fechas, corregir omisiones y guardar la tabla. Prueba tres notas diferentes. Descubre que las tareas sin responsable necesitan revisión humana y lo incorpora a sus instrucciones.', steps:['Describe el procedimiento con verbos concretos: recibir, clasificar, comprobar y guardar.','Prueba tres muestras distintas. Registra qué datos faltan y qué decisiones requieren tu intervención.','Guarda una plantilla con las instrucciones y un ejemplo correcto. Mide el tiempo completo, incluida la revisión.'], deliver:'Un procedimiento de una página y tres resultados revisados.', criterion:'Otra persona puede seguir tus pasos y sabe cuándo detenerse para consultar un dato.', link:'kits', cta:'Consultar los kits de trabajo' },
  { slug:'fase-03-construccion-de-proyectos', title:'Construye un proyecto pequeño y utilizable', goal:'Reunir lo aprendido en una entrega que resuelva un problema concreto.', concept:'Un proyecto no se define por la cantidad de funciones. Se define por el problema que resuelve y por la posibilidad de usarlo. Delimita una primera versión: una página que recoge solicitudes, una hoja que calcula importes o una biblioteca que permite encontrar documentos. Separa lo imprescindible de las mejoras futuras.', example:'Ana crea un registro de tareas con cuatro campos: descripción, responsable, fecha y estado. La primera versión permite crear y consultar una tarea. Los recordatorios quedan para después. Comprueba una tarea completa y otra sin fecha, para que la entrega no dependa de un único ejemplo perfecto.', steps:['Escribe quién usará el proyecto, qué podrá hacer y qué quedará fuera de esta versión.','Construye un recorrido completo con datos ficticios. Comprueba primero que funciona; después mejora su presentación.','Abre la entrega desde el punto de vista de quien la recibirá. Corrige instrucciones, permisos y errores que impidan usarla.'], deliver:'Una primera versión funcional, sus instrucciones y una lista de comprobaciones realizadas.', criterion:'La persona destinataria completa la tarea principal sin necesitar tu conversación con la IA.', link:'mi-proyecto', cta:'Organizar mi proyecto' },
  { slug:'fase-04-automatizacion-agentes-y-sistemas', title:'Automatiza un proceso que ya funciona', goal:'Distinguir qué pasos pueden ejecutarse solos y cuáles necesitan una decisión humana.', concept:'Una automatización ejecuta pasos cuando ocurre un evento, por ejemplo cuando llega una fila nueva. Un agente puede elegir acciones para alcanzar un objetivo dentro de los límites que le das. Ninguno elimina la necesidad de comprobar datos, permisos y resultados. Empieza con un flujo corto y observa cada paso antes de dejarlo activo.', example:'Una nueva solicitud con identificador SOL-001 activa un flujo: validar campos, comprobar si ya existe y guardar. Si llega de nuevo SOL-001, se reconoce como repetición. Si falta el correo, la solicitud queda pendiente de revisión. El primer ensayo utiliza un destino de prueba.', steps:['Dibuja el evento de inicio, la validación y el resultado. Indica qué aplicación realiza cada paso.','Configura conexiones de prueba y ejecuta una muestra válida. Inspecciona los datos de entrada y salida de cada paso.','Prueba una muestra incompleta y una repetida. Define quién recibe el aviso de fallo y cómo se detiene el proceso.'], deliver:'Un flujo probado y un registro de las tres ejecuciones: válida, incompleta y repetida.', criterion:'Puedes explicar qué lo activa, dónde se guardan los datos, cómo evita duplicados y qué ocurre si falla.', link:'automatizaciones', cta:'Estudiar una automatización' },
  { slug:'fase-05-produccion-portfolio-y-escala', title:'Entrega, documenta y mejora', goal:'Preparar una entrega mantenible y demostrar qué has aprendido.', concept:'Terminar significa que otra persona puede utilizar el resultado y que sabes mantenerlo. Documenta cómo arrancar, qué permisos necesita, qué casos has probado y cuáles siguen pendientes. Publicar una web, compartir un documento y activar un flujo son entregas distintas: comprueba la forma de acceso que realmente utilizará el destinatario.', example:'Ana entrega su registro con una guía breve, ejemplos y una versión identificable. Durante tres tareas mide el tiempo de preparación y revisión. Informa del tiempo observado y de los errores encontrados, sin convertir tres pruebas en una promesa de ahorro permanente.', steps:['Repite el recorrido principal desde una sesión o copia nueva usando únicamente tus instrucciones.','Guarda una versión que puedas recuperar y explica quién podrá consultar o modificar la entrega.','Prepara una demostración breve: problema, funcionamiento, pruebas, límites y siguiente mejora.'], deliver:'La entrega accesible, una guía de uso y un resumen de evidencias y límites.', criterion:'Puedes demostrar el resultado, recuperar una versión anterior y explicar qué mantenimiento necesita.', link:'mi-proyecto', cta:'Preparar mi entrega' },
] as const

const translations = [
 ['Define your starting point','Choose one useful task and a result you can verify.','Start with a task you already understand: summarizing notes, organizing requests or preparing an information page. Use a small fictional sample and solve it manually first. That gives you a reference against which to check the tool.','Ana turns meeting notes into a table of tasks, owners and dates. Missing dates must remain unspecified; no messages are sent.',['Describe the task, its recipient and your current method.','Prepare a short fictional sample and a correct reference result.','Identify what you can already do and choose one suitable tool.'],'A brief containing your task, sample, expected result and practice time.','You can name the output and three conditions it must satisfy.','Choose a tool'],
 ['Understand and practise the foundations','Explain the decisions behind an instruction and its result.','Instructions describe the task; context supplies the information. An AI response is a proposal to review. Fluent writing can contain invented facts. Compare every name, number and date with the source and distinguish evidence from inference.','The note says Ana prepares a quote Tuesday and Luis reviews Thursday. The table has two rows and does not invent an amount or a calendar date.',['Read the worked example in the first tool units.','Complete the practice and compare each fact with its source.','Change one input and explain how the result changes.'],'The source, instruction and corrected result with reasons for your edits.','You can repeat the exercise and identify an unsupported claim.','Study a tool'],
 ['Apply learning to a complete task','Create a procedure you can repeat.','A procedure has inputs, steps and outputs. Carry it out manually before automating it. If your criteria change on every attempt, the automation has no stable rule to follow. Record missing information and decisions that need a person.','Ana extracts tasks from three different notes. She discovers that missing owners require human review and records this in her instructions.',['Describe the procedure using concrete actions.','Try three different samples and record exceptions.','Save a template and measure total time including review.'],'A one-page procedure and three reviewed results.','Someone else can follow the steps and knows when to request missing information.','Explore work kits'],
 ['Build a small, usable project','Combine your learning into a deliverable that solves one problem.','Define the user and their main task before choosing features. Build one complete route with fictional data. A useful first version might be a request page, a calculation sheet or a document library. Record future improvements separately.','Ana creates a task register with description, owner, date and status. Creating and reading a task are in scope; reminders come later.',['Define the user, main action and limits of the first version.','Build and test one complete route before polishing its appearance.','Try the deliverable with the recipient’s permissions and instructions.'],'A working first version, instructions and a record of checks.','The recipient completes the main task without your AI conversation.','Organize my project'],
 ['Automate a working process','Separate automatic steps from decisions requiring human judgment.','An automation runs steps in response to an event. An agent can choose actions within defined boundaries. Both require valid inputs and checked outputs. Start with a short flow in a test destination and inspect each intermediate result.','Request REQ-001 is validated, checked for an existing identifier and saved. A replay does not create a duplicate. A request with no email is held for review.',['Draw the trigger, validation and destination.','Configure test connections and inspect a valid run.','Test missing data and replay; define failure reporting and how to stop the flow.'],'A tested flow with valid, incomplete and repeated execution records.','You can explain its trigger, storage, duplicate handling and failure behavior.','Study an automation'],
 ['Deliver, document and improve','Make the result maintainable and demonstrate your learning.','A finished project can be used by another person. Record startup instructions, permissions, tested cases and limitations. Publishing a page, sharing a document and enabling a flow require different access checks. Verify the actual path your recipient will use.','Ana hands over the register with instructions and an identifiable version. She reports time measured on three tasks, including review, without treating it as a guaranteed saving.',['Repeat the main route from a clean session using only your instructions.','Keep a recoverable version and document recipient permissions.','Demonstrate the problem, result, evidence, limitations and next improvement.'],'An accessible deliverable, usage guide and evidence summary.','You can demonstrate the result, restore a version and explain maintenance.','Prepare my delivery'],
] as const

export const isLearningPhase = (slug:string) => slug === 'fases-de-la-formacion' || phases.some(p=>p.slug===slug) || ['matriz-de-proyectos-reales-por-fase','fases-divididas-en-basico-intermedio-y-avanzado'].includes(slug)
export default function LearningPhases({slug}:{slug:string}) {
 const en=useLocale()==='en'
 const selected=phases.findIndex(p=>p.slug===slug)
 const title=en?'Your learning programme':'Tu programa de aprendizaje'
 return <article className="st-page st-path-detail st-phase-guide"><header className="st-lesson-head"><span className="st-kicker">{en?'Student orientation':'Orientación para el alumno'}</span><h1>{selected<0?title:en?translations[selected][0]:phases[selected].title}</h1><p>{en?'Follow six stages: understand a task, practise with a tool, apply it, build a project, automate and deliver. Advance when you can show the result described in each stage.':'El recorrido tiene seis fases: comprender una tarea, practicar con una herramienta, aplicarla, construir un proyecto, automatizar y entregar. Avanza cuando puedas mostrar el resultado indicado en cada fase.'}</p><SaveResourceButton resource={{id:`lesson:${slug}`,kind:'lesson',title,href:href({name:'leccion',slug})}}/></header>
 <nav className="st-unit-contents" aria-label={en?'Programme stages':'Fases del programa'}>{phases.map((p,i)=><a key={p.slug} href={href({name:'leccion',slug:p.slug})}>{String(i).padStart(2,'0')} · {en?translations[i][0]:p.title}</a>)}</nav>
 {phases.map((p,i)=> {if(selected>=0&&selected!==i)return null;const t=translations[i];return <section className="st-panel" key={p.slug}><span className="st-kicker">{en?'Stage':'Fase'} {String(i).padStart(2,'0')}</span><h2>{en?t[0]:p.title}</h2><p><strong>{en?t[1]:p.goal}</strong></p><p>{en?t[2]:p.concept}</p><h3>{en?'Worked example':'Ejemplo resuelto'}</h3><p>{en?t[3]:p.example}</p><h3>{en?'What you will do':'Qué vas a hacer'}</h3><ol className="st-path-steps">{(en?t[4]:p.steps).map(s=><li key={s}>{s}</li>)}</ol><div className="st-unit-evidence"><h3>{en?'What you will submit':'Qué vas a entregar'}</h3><p>{en?t[5]:p.deliver}</p><h3>{en?'Ready to advance when…':'Puedes avanzar cuando…'}</h3><p>{en?t[6]:p.criterion}</p></div><a className="st-btn" href={href({name:p.link})}>{en?t[7]:p.cta}</a></section>})}
 </article>
}
