import {useId,useState} from 'react'
import {useLocale} from '../i18n'
import type {ProjectManual} from '../types'
import {copyText} from '../clipboard'
import {downloadTextFile} from '../editable-template'
export default function PracticeWorkspace({manual:m}:{manual:ProjectManual}){
 const en=useLocale()==='en',t=(es:string,english:string)=>en?english:es,id=useId()
 const example=m.practiceLab?.source||m.inputs.map(i=>i.field+': '+i.example).join('\n')
 const [name,setName]=useState(''),[input,setInput]=useState(''),[goal,setGoal]=useState(''),[observed,setObserved]=useState(''),[status,setStatus]=useState('')
 const values=[name,input,goal],ready=values.every(x=>x.trim())
 const prompt=t(`Ayúdame a aplicar esta práctica a mi tarea: ${m.title}.\nMI TAREA: ${name||'[NOMBRE DE MI TAREA]'}\nMIS DATOS:\n${input||'[MIS DATOS]'}\nLO QUE NECESITO OBTENER:\n${goal||'[RESULTADO QUE NECESITO]'}\n\nREFERENCIA DE LA LECCIÓN:\n${example}\nRESULTADO DEL EJEMPLO:\n${m.practiceLab?.answer||m.outcome}\n\nPrepara el resultado con MIS DATOS, sin confundirlos con los del ejemplo. Si falta información, señala el hueco y haz una pregunta concreta. Explica cada cambio con palabras sencillas. Si necesito una aplicación, dime cuál abrir, qué introducir y qué comprobar. No afirmes haber enviado, guardado o ejecutado nada. Dame primero una versión que pueda revisar; después explica cómo repetirla mañana con otros datos.`,
 `Help me apply this practice to my task: ${m.title}.\nMY TASK: ${name||'[MY TASK NAME]'}\nMY DETAILS:\n${input||'[MY DETAILS]'}\nTHE RESULT I NEED:\n${goal||'[REQUIRED RESULT]'}\n\nLESSON REFERENCE:\n${example}\nEXAMPLE RESULT:\n${m.practiceLab?.answer||m.outcome}\n\nPrepare the result using MY DETAILS, keeping them separate from the example. If information is missing, identify the gap and ask one concrete question. Explain each change in simple language. For application steps, name what to open, enter and check. Claim no unobserved sending, saving or execution. First provide a version I can review, then explain how to repeat it tomorrow with other details.`)
 const worksheet=[m.title,t('MI TAREA','MY TASK'),name,t('MIS DATOS','MY DETAILS'),input,t('LO QUE QUIERO OBTENER','THE RESULT I NEED'),goal,t('RESULTADO QUE HE COMPROBADO','RESULT I HAVE CHECKED'),observed,t('MENSAJE PARA EL ASISTENTE','MESSAGE FOR THE ASSISTANT'),prompt].join('\n\n')
 return <section className="st-panel st-template-editor st-practice-workspace">
 <span className="st-kicker">{t('Úsalo con tus datos','Use it with your details')}</span><h2>{t('Prepara tu versión aquí','Prepare your version here')}</h2>
 <p>{t('Después de entender el ejemplo, completa esta ficha. Puedes copiar el encargo o descargar tu plantilla para seguir trabajando. Estos campos preparan texto: no modifican los archivos de código ni conectan tus cuentas.','After understanding the example, fill in this worksheet. Copy the brief or download your template to keep working. These fields prepare text: they do not change code files or connect accounts.')}</p>
 <div className="st-template-fields">{[[t('1. ¿Qué tarea vas a resolver?','1. Which task will you solve?'),name,setName],[t('2. Pega los datos con los que vas a trabajar','2. Paste the details you will work with'),input,setInput],[t('3. ¿Qué necesitas tener al terminar?','3. What do you need when finished?'),goal,setGoal],[t('4. Cuando lo pruebes: ¿qué resultado obtuviste?','4. After trying it: what result did you get?'),observed,setObserved]].map(([label,value,set],i)=><div key={i}><label htmlFor={`${id}-${i}`}>{label as string}</label><textarea id={`${id}-${i}`} value={value as string} rows={i===1?6:3} onChange={e=>{(set as (v:string)=>void)(e.target.value);setStatus('')}}/></div>)}</div>
 <button type="button" className="st-btn-ghost" onClick={()=>{setName(m.title);setInput(example);setGoal(m.practiceLab?.answer||m.outcome);setObserved('');setStatus(t('Ejemplo cargado. Cambia los datos para preparar tu caso.','Example loaded. Change the details to prepare your case.'))}}>{t('Rellenar con el ejemplo para practicar','Fill with the example to practise')}</button>
 <details className="st-template-preview"><summary>{t('Ver mi encargo antes de copiar','Preview my brief before copying')}</summary><pre>{prompt}</pre></details>
 <div className="st-template-actions"><button type="button" className="st-btn" disabled={!ready} onClick={async()=>{try{await copyText(prompt);setStatus(t('Encargo copiado.','Brief copied.'))}catch{setStatus(t('No se pudo copiar. Utiliza la descarga.','Could not copy. Use the download.'))}}}>{t('Copiar encargo con mis datos','Copy brief with my details')}</button><button type="button" className="st-btn-ghost" onClick={()=>downloadTextFile(en?'my-practice.txt':'mi-practica.txt',worksheet)}>{t('Descargar mi plantilla editable','Download my editable template')}</button></div>
 {!ready&&<p>{t('Completa los tres primeros campos para copiar un encargo con tus datos. Puedes descargar la plantilla vacía.','Fill the first three fields to copy a brief with your details. You can download the blank template.')}</p>}<p role="status">{status}</p>
 </section>
}
