import LearningFlow from './LearningFlow'
import PracticeLabView from './PracticeLabView'
import N8nImportHelp, {isN8nFile} from './N8nImportHelp'
import { useState } from 'react'
import type { ProjectManual } from '../types'
import { useLocale } from '../i18n'
import { copyText } from '../clipboard'

function downloadText(name: string, content: string) {
 const url = URL.createObjectURL(new Blob([content], { type: name.endsWith('.json') ? 'application/json;charset=utf-8' : 'text/plain;charset=utf-8' }))
 const a = document.createElement('a'); a.href = url; a.download = name; a.click(); window.setTimeout(() => URL.revokeObjectURL(url), 1000)
}
function CopyBlock({text,label}:{text:string;label:string}) {
 const [state,setState]=useState('')
 const en=useLocale()==='en'
 return <div className="st-project-code"><button type="button" className="st-btn-ghost" onClick={async()=>{try{await copyText(text);setState(en?'Copied':'Copiado')}catch{setState(en?'Select the text and copy it manually':'Selecciona el texto y cópialo manualmente')}}}>{state||label}</button><span role="status" className="sr-only">{state}</span><pre className="st-institutional-code"><code>{text}</code></pre></div>
}
function ExampleResult({text}:{text:string}) {
 const rows=text.split('\n').map(row=>row.split('|').map(cell=>cell.trim()))
 if(rows.length>1&&rows[0].length>1&&rows.every(row=>row.length===rows[0].length))return <div className="st-project-table"><table><thead><tr>{rows[0].map((cell,i)=><th key={i} scope="col">{cell}</th>)}</tr></thead><tbody>{rows.slice(1).map((row,i)=><tr key={i}>{row.map((cell,j)=><td key={j}>{cell}</td>)}</tr>)}</tbody></table></div>
 return <p style={{whiteSpace:'pre-line'}}>{text}</p>
}
export default function ProjectManualView({manual:m}:{manual:ProjectManual}) {
 const en=useLocale()==='en',t=(es:string,english:string)=>en?english:es
 const [downloadState,setDownloadState]=useState<'idle'|'loading'|'done'|'error'>('idle')
 const [showVisual,setShowVisual]=useState(false)
 const downloadAll=async()=>{setDownloadState('loading');try{const {downloadPractice}=await import('../practice-download');await downloadPractice(m,en);setDownloadState('done')}catch{setDownloadState('error')}}
 return <div className="st-project-manual" lang={m.language || (en ? 'en' : 'es')}>

  <nav className="st-unit-contents" aria-label={t('Índice del proyecto','Project contents')}>{[['brief',t('Preparación','Preparation')],['build',t('Hazlo paso a paso','Build step by step')],['prompts','Prompts'],['files',t('Archivos','Files')],['tests',t('Pruebas','Tests')],['production',t('Proyecto real','Real project')]].map(([id,label])=><button key={id} type="button" onClick={()=>document.getElementById(`project-${id}`)?.scrollIntoView({block:'start'})}>{label}</button>)}</nav>
  <section className="st-panel st-practice-download"><h2>{t('Todo lo necesario para esta práctica','Everything for this practice')}</h2><p>{t('Descarga las instrucciones, los mensajes de ayuda y los archivos juntos. Extrae el ZIP y abre EMPIEZA-AQUI.txt para saber qué hacer con cada material.','Download the instructions, help messages and files together. Extract the ZIP and open START-HERE.txt to see what to do with each item.')}</p><button type="button" className="st-btn" disabled={downloadState==='loading'} onClick={downloadAll}>{downloadState==='loading'?t('Preparando archivos…','Preparing files…'):t('Descargar esta práctica','Download this practice')}</button><p role="status">{downloadState==='done'?t('Paquete preparado. Comprueba la carpeta Descargas.','Package prepared. Check your Downloads folder.'):downloadState==='error'?t('No se ha podido preparar el paquete completo. Inténtalo de nuevo o utiliza las descargas individuales del apartado Archivos.','The full package could not be prepared. Try again or use the individual downloads under Files.'):''}</p></section>
  {m.workedExample && <section className="st-panel st-worked-example" aria-label={t('Ejemplo resuelto','Worked example')}><span className="st-kicker">{t('Mira el resultado antes de empezar','See the result before starting')}</span><h2>{t('Así funciona el ejemplo','How the example works')}</h2><ol className="st-path-steps">{[[t('Con qué empiezas','What you start with'),m.workedExample.before],[t('Qué haces','What you do'),m.workedExample.action],[t('Qué debería aparecer','What should appear'),m.workedExample.after]].map(([label,text])=><li key={label}><strong>{label}</strong><ExampleResult text={text}/></li>)}</ol><p>{t('Este es el resultado de referencia. Sigue los pasos de abajo y compáralo con lo que aparezca en tu pantalla.','This is the reference result. Follow the steps below and compare it with what appears on your screen.')}</p></section>}
  {m.practiceLab&&<PracticeLabView lab={m.practiceLab}/>}
  <LearningFlow manual={m}/>
  {m.visualGuide&&<details className="st-panel st-visual-guide" onToggle={event=>setShowVisual(event.currentTarget.open)}><summary>{t('Ver dónde escribir en la herramienta','See where to type in the tool')}</summary>{showVisual&&<figure><img src={m.visualGuide.src} alt={m.visualGuide.alt} loading="lazy" decoding="async" style={{width:'100%',height:'auto'}}/><figcaption>{m.visualGuide.caption} <a href={m.visualGuide.src} target="_blank" rel="noreferrer">{t("Ampliar imagen", "Enlarge image")}</a> · <a href={m.visualGuide.source} target="_blank" rel="noreferrer">{t('Guía oficial','Official guide')}</a></figcaption></figure>}<ol>{m.visualGuide.points.map(p=><li key={p}>{p}</li>)}</ol></details>}
  <section id="project-brief" className="st-panel"><span className="st-kicker">{t('Proyecto de principio a fin','End-to-end project')}</span><h2>{m.title}</h2><p><strong>{m.outcome}</strong></p>{m.context.map((p,i)=><p key={i}>{p}</p>)}<h3>{t('Qué necesitas y cómo prepararlo','Requirements and preparation')}</h3>{m.prerequisites.map((p,i)=><div className="st-project-step" key={i}><h4>{p.name}</h4><p>{p.instruction}</p><p><strong>{t('Comprueba: ','Check: ')}</strong>{p.check}</p></div>)}<h3>{t('Los datos del ejemplo, uno a uno','The example details, one by one')}</h3><div className="st-project-table"><table><thead><tr><th>{t('Campo','Field')}</th><th>{t('Ejemplo','Example')}</th><th>{t('Regla','Rule')}</th></tr></thead><tbody>{m.inputs.map((p,i)=><tr key={i}><td><code>{p.field}</code></td><td>{p.example}</td><td>{p.rule}</td></tr>)}</tbody></table></div></section>
  <section id="project-build" className="st-panel"><h2>{t('Qué tienes que hacer en cada paso','What to do at each step')}</h2>{m.steps.map((s,i)=><div id={'project-step-'+i} className="st-project-step" key={i}><span className="st-kicker">{t('Paso','Step')} {i+1}</span><h3>{s.title}</h3><p>{s.instruction}</p><p><strong>{t('Por qué: ','Why: ')}</strong>{s.why}</p>{s.configuration&&<CopyBlock text={s.configuration} label={t('Copiar configuración','Copy configuration')}/>}<div className="st-unit-evidence"><strong>{t('Lo que debes ver','What you should see')}</strong><p>{s.expected}</p></div></div>)}</section>
  <section id="project-prompts" className="st-panel"><h2>{t('Mensajes para pedir ayuda a la IA','Messages to ask AI for help')}</h2><p>{t('Cada encargo indica dónde utilizarlo, qué datos sustituir y cómo evaluar la respuesta. La IA ayuda a preparar y revisar; la ejecución y sus resultados se comprueban en la herramienta.','Each brief states where to use it, what to replace and how to judge the response. Verify execution and results in the actual tool.')}</p>{m.prompts.map((p,i)=><div className="st-project-step" key={i}><h3>{p.title}</h3><p><strong>{t('Dónde: ','Where: ')}</strong>{p.where}</p><p><strong>{t('Personaliza: ','Customize: ')}</strong>{p.replace}</p><CopyBlock text={p.text} label={t('Copiar prompt completo','Copy complete prompt')}/><h4>{t('Cómo reconocer una respuesta útil','Recognize a useful answer')}</h4><p>{p.expected}</p><h4>{t('Si la respuesta no sirve, continúa con esto','If the response misses the target, continue with this')}</h4><CopyBlock text={p.followUp} label={t('Copiar corrección','Copy correction')}/></div>)}</section>
  <section id="project-files" className="st-panel"><h2>{t('Materiales y archivos del proyecto','Project files and materials')}</h2>{m.files.map((f,i)=><div className="st-project-step" key={i}><h3>{f.name}</h3><p>{f.purpose}</p>{isN8nFile(f)&&<N8nImportHelp file={f}/>}{f.url&&<a className="st-btn" href={f.url} download>{t('Descargar archivo','Download file')}</a>}{f.content&&<><button className="st-btn-ghost" type="button" onClick={()=>downloadText(f.name,f.content!)}>{t('Descargar archivo','Download file')}</button><CopyBlock text={f.content} label={t('Copiar contenido','Copy contents')}/></>}</div>)}</section>
  <section id="project-tests" className="st-panel"><h2>{t('Pruebas con resultados esperados','Tests with expected results')}</h2>{m.tests.map((p,i)=><div className="st-project-step" key={i}><h3>{i+1}. {p.name}</h3><p><strong>{t('Prepara: ','Prepare: ')}</strong>{p.input}</p><p><strong>{t('Debe ocurrir: ','Expected: ')}</strong>{p.expected}</p><p><strong>{t('Dónde comprobarlo: ','Inspect: ')}</strong>{p.inspect}</p></div>)}<h3>{t('Diagnóstico de errores','Troubleshooting')}</h3>{m.troubleshooting.map((p,i)=><details className="st-project-step" key={i}><summary>{p.symptom}</summary><p><strong>{t('Causa que debes investigar: ','Investigate: ')}</strong>{p.cause}</p><p>{p.fix}</p></details>)}</section>
  <section id="project-production" className="st-panel st-path-check"><h2>{t('Cómo llevarlo a un proyecto real','Moving into a real project')}</h2><ol className="st-path-steps">{m.production.map((p,i)=><li key={i}>{p}</li>)}</ol></section><section className="st-panel"><h2>{t('Documentación para completar la implementación','Implementation references')}</h2>{m.sources.map(s=><p key={s.url}><a href={s.url} target="_blank" rel="noreferrer">{s.title}</a></p>)}</section>
 </div>
}
