import { useState } from 'react'
import { useLocale } from '../i18n'
import { href } from '../router'
import { workspaceText } from '../project-workspace-i18n'
import { store, useStudent } from '../store'
import { emptyWorkspace, impactSummary, milestones, type ProjectWorkspace as Workspace } from '../project-workspace'

export default function ProjectWorkspace() {
  const student = useStudent()
  const locale = useLocale()
  const t = workspaceText(locale)
  const project = student.project
  const [message, setMessage] = useState('')
  const [artifact, setArtifact] = useState({ title: '', url: '', notes: '' })
  const [test, setTest] = useState({ caseName: 'normal', expected: '', actual: '', passed: false })
  const [review, setReview] = useState({ artifactId: '', reviewer: '', feedback: '', status: 'changes_requested' as 'changes_requested' | 'reviewed' })
  if (!project) return <p>{t("Guarda la ficha para abrir el espacio de trabajo.")}</p>
  const workspace = { ...emptyWorkspace(), ...project.workspace, diagnosis: { ...emptyWorkspace().diagnosis, ...project.workspace?.diagnosis }, impact: { ...emptyWorkspace().impact, ...project.workspace?.impact } }
  const update = (patch: Partial<Workspace>) => store.setProject({ ...store.get().project!, workspace: { ...workspace, ...patch }, updatedAt: new Date().toISOString() })
  const summary = impactSummary(workspace.impact)
  const novice = ['novice', 'Empiezo desde cero', 'Starting from scratch'].includes(workspace.diagnosis.experience)
  const recommendedLesson = novice ? 'que-es-la-ia' : ({ web: 'primera-web', app: 'primera-web', datos: 'datos-del-proyecto', automatizar: 'que-automatizar', contenido: 'encargo-comprobable' } as Record<string, string>)[project.projectType || ''] || 'encargo-comprobable'
  return <section className="st-project-workspace">
    <h2>{t("Construcción, evidencias e impacto")}</h2>
    <p>{t("Los resultados y revisiones son registros declarados por ti. La academia no certifica automáticamente una entrega por marcar una casilla.")}</p>
    <details><summary><strong>{t("Punto de partida")}</strong></summary><fieldset><legend>{t("Punto de partida")}</legend>
      <label>{t("Experiencia previa")}<select aria-label={t("Experiencia previa")} value={workspace.diagnosis.experience} onChange={e => update({ diagnosis: { ...workspace.diagnosis, experience: e.target.value } })}><option value="">{t("Selecciona")}</option><option value="novice">{t("Empiezo desde cero")}</option><option value="demo">{t("Ya he construido una demo")}</option><option value="maintainer">{t("Mantengo proyectos en uso")}</option></select></label>
      <label>{t("Horas disponibles por semana")}<input aria-label={t("Horas disponibles por semana")} type="number" min="0" max="168" value={workspace.diagnosis.weeklyHours} onChange={e => update({ diagnosis: { ...workspace.diagnosis, weeklyHours: Math.min(168, Math.max(0, Number(e.target.value))) } })} /></label>
      <label>{t("Restricciones, cuentas y permisos")}<textarea aria-label={t("Restricciones, cuentas y permisos")} value={workspace.diagnosis.constraints} onChange={e => update({ diagnosis: { ...workspace.diagnosis, constraints: e.target.value } })} placeholder={t("Equipo, presupuesto, datos permitidos, permisos pendientes…")} /></label>
    </fieldset>
    <p>{locale === 'en' ? (novice ? 'Start with the foundations before connecting services.' : 'Use your goal to choose the next lesson; return to foundations whenever a prerequisite is missing.') : (novice ? 'Empieza por los fundamentos antes de conectar servicios.' : 'Usa tu objetivo para elegir la siguiente lección; vuelve a fundamentos cuando falte un requisito.')} <a href={href({ name: 'curso', lessonId: recommendedLesson })}>{locale === 'en' ? 'Open recommended lesson' : 'Abrir lección recomendada'}</a></p>
    {workspace.diagnosis.weeklyHours > 0 && workspace.diagnosis.weeklyHours < 3 && <p>{locale === 'en' ? 'With fewer than three hours a week, scope the first milestone to one input, one transformation and one checkable output.' : 'Con menos de tres horas semanales, limita el primer hito a una entrada, una transformación y una salida comprobable.'}</p>}
    </details><details><summary><strong>{t("Hitos del proyecto")}</strong> {Object.values(workspace.milestones).filter(item => item.completed).length}/{milestones.length}</summary>
    {milestones.map(([id, title, hint]) => <fieldset key={id}><legend>{t(title)}</legend><p>{t(hint)}</p><label>{t("Evidencia")}<textarea aria-label={t("Evidencia")} value={workspace.milestones[id]?.evidence || ''} onChange={e => update({ milestones: { ...workspace.milestones, [id]: { evidence: e.target.value, completed: false } } })} /></label><label><input type="checkbox" checked={Boolean(workspace.milestones[id]?.completed)} disabled={!workspace.milestones[id]?.evidence.trim()} onChange={e => update({ milestones: { ...workspace.milestones, [id]: { evidence: workspace.milestones[id].evidence, completed: e.target.checked } } })} />{t("He contrastado esta evidencia con el criterio del hito")}</label></fieldset>)}
    </details><details open><summary><strong>{t("Entregables y resultados")}</strong> {workspace.artifacts.length}</summary>
    <form onSubmit={e => { e.preventDefault(); if (!artifact.title.trim() || (!artifact.url.trim() && !artifact.notes.trim())) return; if (artifact.url.trim()) { try { const url = new URL(artifact.url); if (!['https:', 'http:'].includes(url.protocol)) throw new Error('protocol') } catch { setMessage(locale === 'en' ? 'Use a valid https:// or http:// link.' : 'Usa un enlace válido https:// o http://.'); return } } update({ artifacts: [...workspace.artifacts, { ...artifact, id: crypto.randomUUID(), createdAt: new Date().toISOString() }] }); setArtifact({ title: '', url: '', notes: '' }); setMessage(t('Entregable añadido.')); }}>
      <label>{t("Título")}<input aria-label={t("Título")} required value={artifact.title} onChange={e => setArtifact({ ...artifact, title: e.target.value })} /></label><label>{t("Enlace (opcional)")}<input aria-label={t("Enlace (opcional)")} type="url" pattern="https?://.*" value={artifact.url} onChange={e => setArtifact({ ...artifact, url: e.target.value })} placeholder="https://…" /></label><label>{t("Resultado o evidencia")}<textarea aria-label={t("Resultado o evidencia")} value={artifact.notes} onChange={e => setArtifact({ ...artifact, notes: e.target.value })} /></label><button className="st-btn" disabled={!artifact.title.trim() || (!artifact.url.trim() && !artifact.notes.trim())}>{t("Guardar entregable")}</button>
    </form>
    <ul>{workspace.artifacts.map(item => <li key={item.id}><strong>{item.title}</strong>{/^https?:\/\//i.test(item.url) && <> · <a href={item.url} target="_blank" rel="noreferrer">{t("Abrir")}</a></>}<p style={{ whiteSpace: 'pre-wrap' }}>{item.notes}</p><small>{new Date(item.createdAt).toLocaleString()}</small></li>)}</ul>
    </details><details><summary><strong>{t("Registro de pruebas")}</strong> {workspace.tests.length}</summary><p>{t("Ejecuta la prueba en un entorno controlado y copia lo observado. Un resultado registrado no equivale a una prueba ejecutada por el portal.")}</p>
    <form onSubmit={e => { e.preventDefault(); if (!test.expected.trim() || !test.actual.trim()) return; update({ tests: [...workspace.tests, { ...test, id: crypto.randomUUID(), createdAt: new Date().toISOString() }] }); setTest({ caseName: 'normal', expected: '', actual: '', passed: false }); }}>
      <label>{t("Caso")}<select aria-label={t("Caso")} value={test.caseName} onChange={e => setTest({ ...test, caseName: e.target.value })}>{['normal', 'entrada inválida', 'duplicado', 'fallo de servicio', 'recuperación', 'permisos', 'coste'].map(name => <option key={name} value={name}>{t(name)}</option>)}</select></label><label>{t("Resultado esperado")}<textarea aria-label={t("Resultado esperado")} required value={test.expected} onChange={e => setTest({ ...test, expected: e.target.value })} /></label><label>{t("Resultado observado y evidencia")}<textarea aria-label={t("Resultado observado y evidencia")} required value={test.actual} onChange={e => setTest({ ...test, actual: e.target.value })} /></label><label><input type="checkbox" checked={test.passed} onChange={e => setTest({ ...test, passed: e.target.checked })} />{t("He comprobado que cumple")}</label><button className="st-btn">{t("Registrar prueba")}</button>
    </form>
    <ul>{workspace.tests.map(item => <li key={item.id}><strong>{t(item.caseName)}: {item.passed ? t('cumple (declarado)') : t('pendiente de reparación')}</strong><p>{t("Esperado:")} {item.expected}</p><p>{t("Observado:")} {item.actual}</p></li>)}</ul>
    </details><details><summary><strong>{t("Feedback y nuevas revisiones")}</strong> {workspace.reviews.length}</summary><p>{t("Transcribe una revisión recibida e identifica quién la realizó. Este registro local no suplanta la aprobación de un docente.")}</p>
    <form onSubmit={e => { e.preventDefault(); if (!workspace.artifacts.some(a => a.id === review.artifactId) || !review.reviewer.trim() || !review.feedback.trim()) return; update({ reviews: [...workspace.reviews, { ...review, id: crypto.randomUUID(), createdAt: new Date().toISOString() }] }); setReview({ artifactId: '', reviewer: '', feedback: '', status: 'changes_requested' }); }}><label>{t("Entregable")}<select aria-label={t("Entregable")} required value={review.artifactId} onChange={e => setReview({ ...review, artifactId: e.target.value })}><option value="">{t("Selecciona")}</option>{workspace.artifacts.map(item => <option key={item.id} value={item.id}>{item.title}</option>)}</select></label><label>{t("Autor de la revisión")}<input aria-label={t("Autor de la revisión")} required value={review.reviewer} onChange={e => setReview({ ...review, reviewer: e.target.value })} /></label><label>{t("Feedback y siguiente acción")}<textarea aria-label={t("Feedback y siguiente acción")} required value={review.feedback} onChange={e => setReview({ ...review, feedback: e.target.value })} /></label><label>{t("Resultado")}<select aria-label={t("Resultado")} value={review.status} onChange={e => setReview({ ...review, status: e.target.value as typeof review.status })}><option value="changes_requested">{t("Requiere cambios")}</option><option value="reviewed">{t("Revisado (declarado)")}</option></select></label><button className="st-btn" disabled={!workspace.artifacts.length}>{t("Registrar revisión")}</button></form>
    <ul>{workspace.reviews.map(item => <li key={item.id}><strong>{workspace.artifacts.find(a => a.id === item.artifactId)?.title} · {item.reviewer}</strong><p>{item.feedback}</p><small>{item.status === 'reviewed' ? t('Revisado (declarado)') : t('Requiere cambios')} · {new Date(item.createdAt).toLocaleString()}</small></li>)}</ul>
    </details><details><summary><strong>{t("Impacto y operación")}</strong> </summary><p>{t("Incluye el tiempo de revisión y reparación en el tiempo posterior. Usa el mismo tipo de tarea y una muestra comparable.")}</p>
    {([['baselineMinutes', 'Minutos manuales por tarea'], ['afterMinutes', 'Minutos por tarea con el sistema y revisión'], ['weeklyRuns', 'Tareas por semana'], ['weeklyCost', 'Coste semanal (€)'], ['hourlyValue', 'Valor de una hora (€)'], ['baselineErrors', 'Errores en la muestra anterior'], ['afterErrors', 'Errores en la muestra posterior']] as const).map(([key, label]) => <label key={key}>{t(label)}<input type="number" min="0" step="0.01" value={workspace.impact[key]} onChange={e => update({ impact: { ...workspace.impact, [key]: Math.max(0, Number(e.target.value)) } })} /></label>)}
    <p><strong>{t("Ahorro estimado:")} {summary.weeklyMinutes.toFixed(1)} {t("min/semana. Valor neto estimado:")} {summary.weeklyNet.toFixed(2)} {t("€/semana.")}</strong>{t("Son cálculos de los datos que introduces, no mediciones automáticas.")}</p>
    <label>{t("Periodo, tamaño de muestra, fuente de datos y decisión")}<textarea aria-label={t("Periodo, tamaño de muestra, fuente de datos y decisión")} value={workspace.impact.observations} onChange={e => update({ impact: { ...workspace.impact, observations: e.target.value } })} /></label><label>{t("Responsable de operación")}<input aria-label={t("Responsable de operación")} value={workspace.impact.owner} onChange={e => update({ impact: { ...workspace.impact, owner: e.target.value } })} /></label><label>{t("Próxima revisión")}<input aria-label={t("Próxima revisión")} type="date" value={workspace.impact.reviewDate} onChange={e => update({ impact: { ...workspace.impact, reviewDate: e.target.value } })} /></label><p>{t("La fecha queda registrada; no programa un aviso externo.")}</p><label>{t("Cómo apagar, recuperar, verificar y entregar el sistema")}<textarea aria-label={t("Cómo apagar, recuperar, verificar y entregar el sistema")} value={workspace.impact.runbook} onChange={e => update({ impact: { ...workspace.impact, runbook: e.target.value } })} /></label>
    </details><p role="status">{message}</p>
  </section>
}
