import ProjectManualView from './ProjectManualView'
import { useEffect, useState } from 'react'
import type { ToolPage } from '../types'
import type { PathLesson } from '../tool-path'
import { href } from '../router'
import { store, useStudent } from '../store'
import { useLocale } from '../i18n'
import SaveResourceButton from './SaveResourceButton'

export default function ToolLearningPath({ tool, lessonId }: { tool: ToolPage; lessonId?: string }) {
  const en = useLocale() === 'en'
  const student = useStudent()
  const [need, setNeed] = useState('all')
  const [fallback,setFallback]=useState<PathLesson[]>([])
  useEffect(()=>{let cancelled=false;if(!tool.guide?.projectLessons?.length)void import('../tool-path').then(({toolPath})=>{if(!cancelled)setFallback(toolPath(tool,en))});return()=>{cancelled=true}},[tool,en])
  const lessons:PathLesson[]=tool.guide?.projectLessons?.length?tool.guide.projectLessons.map((project,index)=>({id:String(index+1).padStart(2,'0'),title:project.title.replace(/^\d+ · /,''),purpose:project.outcome,explanation:[],example:'',steps:[],check:'',errors:[]})):fallback
  const url = (id?: string) => href({ name: 'herramienta', toolId: tool.id, tab: 'lecciones-herramienta', lessonId: id, filters: {} })
  const done = (id: string) => student.lessons[`tool-path:${tool.id}:${id}`]?.done.includes('intermedio')
  const active = lessons.find(item => item.id === lessonId)
  const manual = active ? tool.guide?.projectLessons?.[Number(active.id)-1] : undefined
  if(!lessons.length)return <p role="status">{en?'Loading lessons…':'Cargando lecciones…'}</p>
  if (lessonId && !active) return <div className="st-page"><h1>{en ? 'Lesson not found' : 'Lección no encontrada'}</h1><a href={url()}>{en ? 'Back to lessons' : 'Volver a las lecciones'}</a></div>
  if (active) return <article className="st-page st-path-detail">
    <a className="st-btn-ghost" href={url()}>{en ? `Back to ${tool.label}` : `Volver a ${tool.label}`}</a>
    <header className="st-lesson-head"><span className="st-kicker">{tool.label} · {en ? 'Lesson' : 'Lección'} {active.id} / 10</span><h1>{active.title}</h1><p className="st-lesson-headline">{active.purpose}</p><SaveResourceButton resource={{ id: `tool-path:${tool.id}:${active.id}`, kind: 'lesson', title: `${tool.label} · ${active.title}`, href: url(active.id) }} /></header>
    {manual ? <ProjectManualView manual={manual}/> : <>
    <div className="st-unit-intro"><p><strong>{en ? 'Study time' : 'Dedicación orientativa'}:</strong> {active.study?.minutes || 45} {en ? 'minutes, including practice' : 'minutos, incluida la práctica'}</p><p>{Number(active.id) === 1 ? (en ? 'Prerequisites: a practice space, the sample below and time to review your result. No previous project is required.' : 'Antes de empezar: prepara un espacio de práctica, la muestra de esta unidad y tiempo para revisar el resultado. No necesitas un proyecto previo.') : (en ? 'Before you start: keep the source sample and the work from the previous unit. If you enter here directly, read the worked example and prepare those materials first.' : 'Antes de empezar: conserva la muestra original y el trabajo de la unidad anterior. Si has entrado directamente aquí, lee el ejemplo resuelto y prepara primero esos materiales.')}</p></div>
    <nav className="st-unit-contents" aria-label={en ? 'Unit contents' : 'Contenido de la unidad'}>{[['concepts',en?'Understand':'Comprender'],['worked',en?'Worked example':'Ejemplo resuelto'],['practice',en?'Guided practice':'Práctica guiada'],['independent',en?'Your exercise':'Tu ejercicio'],['evidence',en?'Evidence':'Comprobación']].map(([id,label])=><button type="button" key={id} onClick={()=>document.getElementById(`unit-${id}`)?.scrollIntoView({block:'start'})}>{label}</button>)}</nav>
    <section id="unit-concepts" className="st-panel"><span className="st-kicker">01 · {en?'Conceptual foundation':'Fundamentos'}</span><h2>{en ? 'Understand what you are going to do' : 'Comprende lo que vas a hacer'}</h2>{active.study ? active.study.concepts.map((concept,i)=><div key={i}><h3>{concept.title}</h3>{concept.paragraphs.map((text,j)=><p key={j}>{text}</p>)}</div>) : active.explanation.map((text,i)=><p key={i}>{text}</p>)}</section>
    <section id="unit-worked" className="st-panel"><span className="st-kicker">02 · {en?'Demonstration':'Resolución comentada'}</span><h2>{en ? 'A worked example to study' : 'Un ejemplo resuelto para estudiar'}</h2><h3>{en?'Starting situation':'Situación de partida'}</h3><p>{active.example}</p>{active.study&&<><h3>{en?'Reference solution':'Modelo de resolución'}</h3><div className="st-worked-solution">{active.study.solution.includes('\n')?<pre className="st-institutional-code"><code>{active.study.solution}</code></pre>:<p>{active.study.solution}</p>}</div><h3>{en?'Why it is resolved this way':'Por qué se resuelve así'}</h3><p>{active.study.reasoning}</p><p className="st-unit-note">{en?'This is the reference for the exercise. Compare it with your own execution; it is not a result already produced in your account.':'Este es el modelo del ejercicio. Compáralo con tu ejecución; no es un resultado ya producido en tu cuenta.'}</p></>}</section>
    <section id="unit-practice" className="st-panel"><span className="st-kicker">03 · {en?'Guided practice':'Práctica guiada'}</span><h2>{en ? 'Do it step by step' : 'Hazlo paso a paso'}</h2><p>{en?'Use the same practice case throughout this tool’s programme. Keep the input and your observed result so you can explain each decision.':'Utiliza el mismo caso de práctica a lo largo del recorrido de esta herramienta. Conserva la entrada y el resultado observado para poder explicar cada decisión.'}</p><ol className="st-path-steps">{active.steps.map((text,i)=><li key={i}>{text}</li>)}</ol></section>
    {active.study&&<section id="unit-independent" className="st-panel"><span className="st-kicker">04 · {en?'Independent application':'Aplicación autónoma'}</span><h2>{en?'Now adapt the exercise':'Ahora adapta el ejercicio'}</h2><p>{active.study.exercise}</p><p>{en?'Write your expected result before trying it. Afterwards explain what changed, what remained the same and what still needs review.':'Escribe el resultado que esperas antes de intentarlo. Después explica qué ha cambiado, qué se mantiene y qué necesita todavía revisión.'}</p></section>}
    <section id="unit-evidence" className="st-panel st-path-check"><span className="st-kicker">05 · {en?'Learning evidence':'Evidencia de aprendizaje'}</span><h2>{en?'Check before completing the unit':'Comprueba antes de completar la unidad'}</h2>{active.study?<ul>{active.study.criteria.map((text,i)=><li key={i}>{text}</li>)}</ul>:<p>{active.check}</p>}<p>{en?'Mark completion when you can show these results and explain your procedure. Reading the reference alone does not complete the practice.':'Marca la unidad como completada cuando puedas mostrar estos resultados y explicar el procedimiento. Leer el modelo no sustituye realizar la práctica.'}</p></section>
    <section className="st-panel"><h2>{en ? 'If something goes wrong' : 'Si algo falla'}</h2>{active.errors.map((text,i)=><p key={i}>{text}</p>)}</section>
    <p><a href={tool.guide?.account.url.startsWith('http') ? tool.guide.account.url : `https://${tool.guide?.account.url}`} target="_blank" rel="noreferrer">{en ? 'Official setup reference' : 'Referencia oficial de preparación'}</a></p>
    {tool.id==='codex' && <p><a href="https://nodejs.org/api/assert.html" target="_blank" rel="noreferrer">{en?'Node.js: official assertion reference':'Node.js: referencia oficial de las aserciones'}</a></p>}
    {tool.id==='supabase' && <p><a href="https://supabase.com/docs/guides/database/postgres/row-level-security" target="_blank" rel="noreferrer">{en?'Supabase: row-level access policies':'Supabase: políticas de acceso por fila'}</a></p>}
    </>}
    <button className="st-btn" type="button" aria-pressed={!!done(active.id)} onClick={() => store.toggleDone(`tool-path:${tool.id}:${active.id}`, 'intermedio')}>{done(active.id) ? (en ? 'Completed · undo' : 'Completada · deshacer') : (en ? 'Mark lesson completed' : 'Marcar lección completada')}</button>
    {done(active.id)&&<section className="st-panel st-completion-result" role="status"><span className="st-kicker">{en?'Your saved progress':'Tu avance guardado'}</span><h2>{en?'What you take away':'Qué te llevas de esta práctica'}</h2><p>{active.purpose}</p><p>{en?'Keep your result and the check you performed. This mark records your own confirmation.':'Conserva tu resultado y la comprobación que has hecho. Esta marca guarda tu propia confirmación.'}</p>{lessons[Number(active.id)]?<a className="st-btn" href={url(lessons[Number(active.id)].id)}>{en?'Continue with: ':'Sigue con: '}{lessons[Number(active.id)].title}</a>:<a className="st-btn" href={href({name:'mi-proyecto'})}>{en?'Bring it to my project':'Llévalo a Mi proyecto'}</a>}</section>}
    <nav className="st-lesson-nav" aria-label={en ? 'Lesson navigation' : 'Navegación de lecciones'}>{Number(active.id) > 1 && <a href={url(String(Number(active.id) - 1).padStart(2, '0'))}>{en ? 'Previous' : 'Anterior'}</a>}{Number(active.id) < 10 ? <a href={url(String(Number(active.id) + 1).padStart(2, '0'))}>{en ? 'Next lesson' : 'Siguiente lección'}</a> : <a href={href({ name: 'mi-proyecto' })}>{en ? 'Open my project' : 'Abrir mi proyecto'}</a>}</nav>
  </article>
  return <section className="st-tool-path"><div className="st-section-head"><div><span className="st-kicker">{en ? 'Tool curriculum' : 'Programa de la herramienta'}</span><h2>{en ? `${tool.label}: ten practical learning units` : `${tool.label}: diez unidades de aprendizaje práctico`}</h2><p>{en ? 'Each unit develops concepts, a worked example, guided practice and a personal exercise. Start at 01 and advance when you can demonstrate the learning evidence.' : 'Cada unidad desarrolla conceptos, un ejemplo resuelto, una práctica guiada y un ejercicio propio. Empieza por la 01 y avanza cuando puedas demostrar lo aprendido.'}</p></div><span>{lessons.filter(item => done(item.id)).length}/10</span></div>
    <div className="st-path-needs" role="group" aria-label={en ? 'What do you need?' : '¿Qué necesitas?'}>{[['all', en ? 'All lessons' : 'Todas'], ['start', en ? 'I am starting' : 'Estoy empezando'], ['build', en ? 'I want to create' : 'Quiero crear'], ['fix', en ? 'Fix an error' : 'Arreglar un error'], ['deliver', en ? 'Deliver my project' : 'Entregar mi proyecto']].map(([id, label]) => <button className="st-btn-ghost" type="button" key={id} aria-pressed={id === need} onClick={() => setNeed(id)}>{label}</button>)}</div>
    <ol className="st-path-list">{lessons.filter(item => need === 'all' || ({ start: [1,2,3], build: [4,5,6], fix: [7,8], deliver: [9,10] }[need] || []).includes(Number(item.id))).map(item => <li key={item.id}><a href={url(item.id)}><span className="st-path-number">{item.id}</span><div><h3>{item.title}</h3><p>{item.purpose}</p><small>{tool.guide?.projectLessons ? 60 : item.study?.minutes || 45} {en ? 'min · explanation, worked example and practice' : 'min · explicación, ejemplo y práctica'}</small></div><span>{done(item.id) ? '✓' : '→'}</span></a></li>)}</ol>
    {!!tool.itinerary?.length && <details className="st-panel"><summary>{en ? 'Additional worked lessons' : 'Lecciones resueltas adicionales'}</summary>{tool.itinerary.map(item => <p key={item.id}><a href={href({ name: 'curso', lessonId: item.id })}>{item.title}</a></p>)}</details>}
  </section>
}
