import {useId,useState} from 'react'
import {useLocale} from '../i18n'
import {copyText} from '../clipboard'
import {downloadTextFile} from '../editable-template'
import {personalizeWorkflow,type JsonValue} from '../workflow-personalization'
import type {ProjectManual} from '../types'
const labels:Record<string,[string,string]>={id:['Identificador','Identifier'],text:['Texto','Text'],name:['Nombre','Name'],email:['Correo','Email'],owner:['Responsable','Owner'],message:['Mensaje','Message'],items:['Elementos','Items'],tasks:['Tareas','Tasks'],rows:['Filas','Rows'],status:['Estado','Status'],priority:['Prioridad','Priority'],title:['Título','Title'],done:['Terminada','Completed'],blocked:['Bloqueada','Blocked'],quantity:['Cantidad','Quantity'],amount:['Importe','Amount'],currency:['Moneda','Currency'],phone:['Teléfono','Phone'],description:['Descripción','Description'],approved:['Aprobado','Approved'],confirmed:['Confirmado','Confirmed'],role:['Tipo de usuario','User role'],company:['Empresa','Company'],costCents:['Coste en céntimos','Cost in cents'],subtotalCents:['Subtotal en céntimos','Subtotal in cents'],taxCents:['Impuestos en céntimos','Tax in cents'],totalCents:['Total en céntimos','Total in cents'],incoming:['Datos nuevos','Incoming details'],existing:['Datos existentes','Existing details'],attachments:['Archivos adjuntos','Attachments'],runs:['Ejecuciones','Runs'],variants:['Versiones','Variants'],unsupported:['Afirmaciones sin respaldo','Unsupported claims'],attempt:['Intento actual','Current attempt'],maxAttempts:['Máximo de intentos','Maximum attempts'],delayHours:['Espera en horas','Wait in hours'],retryAfterSeconds:['Espera en segundos','Wait in seconds'],affectedUsers:['Usuarios afectados','Affected users'],consecutiveFailures:['Fallos seguidos','Consecutive failures'],serviceDown:['Servicio caído','Service down'],openIncident:['Incidencia abierta','Open incident'],approvedBy:['Persona que aprobó','Approved by'],approvedVersion:['Versión aprobada','Approved version'],currentVersion:['Versión actual','Current version'],expectedVersion:['Versión esperada','Expected version'],publishedVersion:['Versión publicada','Published version'],version:['Versión','Version'],recordId:['Identificador del registro','Record identifier'],score:['Puntuación','Score'],escalated:['Derivada para revisión','Escalated for review'],createdAt:['Fecha de creación','Creation time'],startedAt:['Hora de inicio','Start time'],endedAt:['Hora de finalización','End time'],startsAt:['Fecha de la reunión','Meeting time'],dueAt:['Fecha límite','Due time'],now:['Hora de referencia de la prueba','Reference time for the test'],requestedDay:['Día solicitado','Requested day']}
function JsonFields({value,onChange,label,en,template}:{value:JsonValue;onChange:(value:JsonValue)=>void;label:string;en:boolean;template?:JsonValue}){
 const id=useId(),display=labels[label]?.[en?1:0]||label
 const help=label==='id'?(en?'Use a code that identifies this item, such as P9. Keep it when testing the same request again.':'Usa un código que identifique este elemento, como P9. Consérvalo cuando vuelvas a probar la misma petición.'):label==='email'?(en?'Use a practice address such as ana@example.com. This local workflow sends no email.':'Utiliza un correo de ensayo, como ana@example.com. Este flujo local no envía correos.'):['text','message','description'].includes(label)?(en?'Write the actual request or description you want this step to process. Read the lesson’s rules to understand its result.':'Escribe la petición o descripción que quieres procesar. Lee las reglas de la lección para entender el resultado.'):label==='priority'?(en?'This example uses alta for high priority and baja for low priority. Keep these literal values.':'Este ejemplo utiliza alta para prioridad alta y baja para prioridad baja. Conserva esas palabras.'):['status','role'].includes(label)?(en?'Use the category values explained by this practice; changing their language changes the input the rule reads.':'Utiliza las categorías explicadas en esta práctica; traducir su nombre cambia el dato que lee la regla.'):/At$/.test(label)||label==='now'?(en?'Keep the example’s date and time format, including its time zone. The reference time is part of the test; it is not updated automatically.':'Conserva el formato de fecha y hora del ejemplo, incluida la zona horaria. La hora de referencia forma parte de la prueba; no se actualiza sola.'):/Cents$/.test(label)?(en?'Enter cents: 100 means one currency unit. The currency is specified separately when needed.':'Escribe céntimos: 100 representa una unidad de moneda. La moneda se indica por separado cuando es necesaria.'):''
 if(value!==null&&typeof value==='object'){
  const array=Array.isArray(value)
  return <fieldset className="st-json-group"><legend>{display}</legend>{Object.entries(value).map(([key,child])=><div key={key}><JsonFields value={child} template={template&&typeof template==='object'?(Array.isArray(template)?template[Number(key)]??template[0]:(template as Record<string,JsonValue>)[key]):undefined} label={array?`${en?'Item':'Elemento'} ${Number(key)+1}`:key} en={en} onChange={changed=>{if(array){const copy=[...value];copy[Number(key)]=changed;onChange(copy)}else onChange({...value,[key]:changed})}}/>{array&&<button type="button" className="st-btn-ghost" onClick={()=>onChange(value.filter((_,i)=>i!==Number(key)))}>{en?'Remove this item':'Quitar este elemento'}</button>}</div>)}{array&&(value.length>0||(Array.isArray(template)&&template.length>0))&&<button type="button" className="st-btn-ghost" onClick={()=>onChange([...value,structuredClone(value[0]??(template as JsonValue[])[0])])}>{en?'Add a copy of the first item':'Añadir una copia del primer elemento'}</button>}{array&&value.length===0&&<p>{en?'Empty list. Use Add to restore one example item.':'Lista vacía. Utiliza Añadir para recuperar un elemento del ejemplo.'}</p>}</fieldset>
 }
 return <div className="st-json-field"><label htmlFor={id}>{display}{labels[label]&&<small> · {label}</small>}</label>{typeof value==='boolean'?<select id={id} value={String(value)} onChange={e=>onChange(e.target.value==='true')}><option value="true">{en?'Yes · true':'Sí · true'}</option><option value="false">{en?'No · false':'No · false'}</option></select>:value===null?<p>{en?'No value · null':'Sin valor · null'}</p>:<input id={id} type={typeof value==='number'?'number':'text'} step={typeof value==='number'?'any':undefined} value={typeof value==='number'&&!Number.isFinite(value)?'':value} onChange={e=>onChange(typeof value==='number'?(e.target.value===''?NaN:Number(e.target.value)):e.target.value)}/>}{help&&<small>{help}</small>}</div>
}
export default function WorkflowInputEditor({file}:{file:ProjectManual['files'][number]}){
 const en=useLocale()==='en',t=(es:string,english:string)=>en?english:es,config=file.personalization!
 const [input,setInput]=useState(config.sample),[status,setStatus]=useState(''),[busy,setBusy]=useState(false)
 const prepare=async(download:boolean)=>{
  setBusy(true);setStatus('')
  try{
   let text=file.content
   if(!text&&file.url){const url=new URL(file.url,location.href);if(url.origin!==location.origin)throw new Error('External file');const r=await fetch(url,{credentials:'same-origin'});if(!r.ok)throw new Error('Download failed');text=await r.text()}
   const value=personalizeWorkflow(JSON.parse(text||''),input,config),result=JSON.stringify(value,null,2)
   if(download)downloadTextFile('my-'+file.name,result);else await copyText(result)
   setStatus(t('Tu flujo está preparado. Impórtalo en un workflow vacío, ejecútalo y abre Resolver para comprobar el resultado con tus datos.','Your workflow is prepared. Import it into an empty workflow, run it and open Resolver to check the result with your details.'))
  }catch(e){setStatus(t('No se ha podido preparar: ','Could not prepare: ')+(e instanceof Error?e.message:''))}finally{setBusy(false)}
 }
 return <details className="st-template-editor st-workflow-personalize"><summary>{t('Preparar este flujo con mis datos','Prepare this workflow with my details')}</summary><p>{t('Cambia los campos de abajo. El archivo nuevo conserva las reglas de Resolver y usa tus datos como entrada. Funciona dentro de n8n; los envíos y guardados en otras aplicaciones requieren las conexiones de la guía.','Change the fields below. The new file keeps Resolver’s rules and uses your details as input. It runs within n8n; sending and saving to other apps require the guide’s connections.')}</p><p>{t('Esta copia termina en Resolver: la caja que compara con la respuesta fija del ejemplo no se incluye, porque tus datos pueden producir otra respuesta. Comprueba tú el resultado antes de utilizarlo. La marca de ejecución del ejemplo original no se aplica a tu copia.','This copy ends at Resolver: the node comparing against the example’s fixed answer is omitted because your details may produce another answer. Check the result yourself before using it. The original example’s execution badge does not apply to your copy.')}</p><JsonFields value={input} template={config.sample} label={t('Datos para tu prueba','Details for your test')} en={en} onChange={x=>{setInput(x as typeof input);setStatus('')}}/><div className="st-template-actions"><button className="st-btn" type="button" disabled={busy} onClick={()=>prepare(false)}>{t('Copiar flujo con mis datos','Copy workflow with my details')}</button><button className="st-btn-ghost" type="button" disabled={busy} onClick={()=>prepare(true)}>{t('Descargar mi flujo JSON','Download my workflow JSON')}</button><button className="st-btn-ghost" type="button" onClick={()=>{setInput(structuredClone(config.sample));setStatus('')}}>{t('Volver a cargar el ejemplo','Reload the example')}</button></div><p role="status">{status}</p></details>
}
