/**
 * Automatizaciones reales por herramienta.
 *
 * Tres grupos, porque no todas las herramientas juegan el mismo papel:
 *
 * - PLATAFORMAS (n8n, Zapier, Make, Pipedream): son el sitio DONDE se montan
 *   automatizaciones. Conservan el recetario general de doce recorridos, que
 *   ahí sí tiene sentido: son recetas de plataforma.
 * - CONECTABLES (este archivo): herramientas con disparadores y acciones
 *   reales que se enganchan a un flujo. Cada una lleva SUS automatizaciones,
 *   escritas con sus disparadores de verdad, no una plantilla con el nombre
 *   cambiado.
 * - EL RESTO: no se automatizan (un editor, una herramienta de dibujo, un
 *   generador de imagen). Su página no lleva la sección, y eso también es
 *   información honesta.
 */

export const AUTOMATION_PLATFORMS = new Set(['n8n', 'zapier', 'make', 'pipedream'])

export const REAL_AUTOMATIONS = {
  /* ── Google Sheets ─────────────────────────────────────────────── */
  sheets: [
    {
      name: 'Fila nueva en la hoja → ficha creada y aviso al responsable',
      goal: 'Que un alta en la hoja (desde un formulario o a mano) dispare el proceso sin que nadie vigile.',
      difficulty: 'basica',
      platform: 'n8n · Google Sheets Trigger',
      trigger: 'El Sheets Trigger de n8n comprueba la hoja cada minuto y entrega solo las filas añadidas desde la última pasada.',
      steps: [
        'Sheets Trigger apuntando a la pestaña de registro, con la fila 1 como nombres de campo (minúsculas, sin acentos).',
        'Filtro: descartar filas de prueba (nombre contiene «test») y filas sin correo.',
        'Comprobar si el correo ya existe en la hoja maestra antes de crear nada: es lo que evita duplicados.',
        'Crear la ficha donde toque (otra hoja, Notion, un CRM) con los campos mapeados.',
        'Escribir en la fila original la marca de procesado: fecha y hora en una columna propia.',
        'Avisar al responsable por Slack o correo con nombre y enlace, solo si el alta es real.',
      ],
      test: 'Añade una fila de verdad, una sin correo y una repetida. Solo la primera debe crear ficha y aviso; las otras dos deben cortarse y quedar marcadas.',
      failure: 'Si la hoja devuelve 404, la credencial no la ve: compártela de nuevo. Si llegan filas duplicadas, alguien insertó filas en medio: el disparador funciona por posición, añade siempre al final.',
      credentials: 'Credencial OAuth de Google con acceso a esa hoja concreta. La marca de procesado hace de red de seguridad si el flujo se relanza.',
    },
    {
      name: 'Resumen diario de la hoja a las 9:00',
      goal: 'Un correo o mensaje cada mañana con los pendientes, sin abrir la hoja.',
      difficulty: 'basica',
      platform: 'n8n · Schedule + Google Sheets',
      trigger: 'Schedule Trigger cada día laborable a las 9:00, zona horaria Europe/Madrid comprobada.',
      steps: [
        'Leer todas las filas de la pestaña de registro.',
        'Filtrar por estado pendiente, comparando en minúsculas y con «contiene», no con «igual exacto».',
        'Agregar los pendientes en una sola lista (nodo Aggregate): un mensaje, no uno por fila.',
        'Si hay cero pendientes, terminar sin enviar: el silencio también es información correcta.',
        'Enviar el resumen con el total y las tres más antiguas destacadas.',
      ],
      test: 'Ejecuta con pendientes y sin pendientes. Con cero, no debe llegar mensaje. Comprueba la hora real del disparo al día siguiente.',
      failure: 'Si el resumen llega a las 7:00, la zona horaria está en UTC. Si llega un mensaje por fila, falta el Aggregate.',
      credentials: 'La misma credencial de Google del flujo anterior; se reutiliza.',
    },
    {
      name: 'Limpieza semanal: mover lo cerrado al histórico',
      goal: 'Que la hoja de trabajo no acumule miles de filas y siga rápida.',
      difficulty: 'intermedia',
      platform: 'n8n · Schedule + Google Sheets',
      trigger: 'Schedule Trigger los domingos a las 22:00.',
      steps: [
        'Leer las filas con estado cerrado y fecha de cierre de hace más de 30 días.',
        'Añadirlas a la pestaña «historico» del mismo documento.',
        'Verificar que el número de filas escritas coincide con las leídas antes de borrar nada.',
        'Borrar del registro solo las filas verificadas, de abajo arriba para no descolocar posiciones.',
        'Apuntar en una celda de control cuántas se movieron y cuándo.',
      ],
      test: 'Prueba con 3 filas cerradas antiguas y 2 recientes: solo las 3 deben moverse. Comprueba que el histórico las tiene ANTES de mirar si el registro las perdió.',
      failure: 'Si el flujo muere entre escribir y borrar, habrá filas duplicadas entre pestañas: mejor duplicadas que perdidas, por eso se escribe primero y se borra después.',
      credentials: 'Google OAuth. Este flujo BORRA datos: pruébalo contra una copia del documento antes de darle la hoja real.',
    },
    {
      name: 'Enriquecer cada alta con IA y clasificarla',
      goal: 'Que cada fila nueva llegue clasificada (tipo de cliente, urgencia) sin trabajo manual.',
      difficulty: 'intermedia',
      platform: 'n8n · Sheets Trigger + modelo de lenguaje',
      trigger: 'Fila nueva en la hoja de entradas.',
      steps: [
        'Recoger el texto libre de la fila (asunto, mensaje del formulario).',
        'Llamar al modelo con salida estructurada: categoría entre valores cerrados, urgencia 1-3, resumen en una frase.',
        'Validar la respuesta contra la lista cerrada; si no encaja, marcar «revisar» en vez de inventar.',
        'Escribir las tres columnas nuevas en la misma fila.',
        'Si urgencia es 3, avisar al momento; el resto entra en el resumen de la mañana.',
      ],
      test: 'Pasa un caso claro, uno ambiguo y uno en blanco. El ambiguo debe salir «revisar», no una categoría inventada con confianza.',
      failure: 'Si el modelo devuelve texto libre en vez de la categoría, endurece el prompt (solo esos valores) o usa salida estructurada del nodo. Nunca escribas en la hoja lo que no pasó la validación.',
      credentials: 'Google OAuth + clave del proveedor de IA con tope de gasto puesto. Coste por fila: céntimos; ponle contador.',
    },
    {
      name: 'Vigilar una celda de umbral y avisar si se cruza',
      goal: 'Enterarte el día que el stock, el saldo o la métrica cruza la línea roja.',
      difficulty: 'basica',
      platform: 'n8n · Schedule + Google Sheets',
      trigger: 'Schedule cada hora en horario laboral.',
      steps: [
        'Leer el rango concreto (una celda o columna calculada en la hoja).',
        'Comparar contra el umbral definido en el propio flujo, no escondido en una fórmula.',
        'Avisar solo si se cruza Y no se avisó ya hoy: guardar la fecha del último aviso en una celda de control.',
        'Incluir en el aviso el valor actual, el umbral y el enlace directo a la hoja.',
      ],
      test: 'Fuerza el valor por debajo del umbral y ejecuta dos veces seguidas: debe avisar la primera y callar la segunda.',
      failure: 'Sin la celda de control, tendrás un aviso por hora hasta que alguien arregle el dato: el flujo se convierte en ruido y lo silencian.',
      credentials: 'Google OAuth y el canal de aviso (Slack, correo o Telegram).',
    },
    {
      name: 'Formulario web → hoja, con validación por medio',
      goal: 'Recoger entradas de tu web en la hoja sin servicios de pago por medio.',
      difficulty: 'intermedia',
      platform: 'n8n · Webhook + Google Sheets',
      trigger: 'Webhook de n8n que recibe el envío del formulario (POST con los campos).',
      steps: [
        'Webhook con respuesta inmediata de «recibido» para que la web no espere.',
        'Validar campos: correo con arroba, teléfono con longitud razonable, honeypot vacío (anti-spam).',
        'Normalizar: minúsculas en el correo, espacios fuera, fecha en formato AAAA-MM-DD.',
        'Añadir la fila con origen «web» y marca de tiempo.',
        'Responder al remitente con el correo de confirmación solo si todo validó.',
      ],
      test: 'Envía el formulario legítimo, uno con el honeypot relleno y uno sin correo. Solo el primero debe llegar a la hoja.',
      failure: 'Si llegan entradas duplicadas, el usuario pulsó dos veces: desactiva el botón al enviar en la web y comprueba existencia por correo+fecha en el flujo.',
      credentials: 'La Production URL del webhook (no la de test) y Google OAuth. El honeypot ahorra el 90% del spam sin captcha.',
    },
  ],

  /* ── WhatsApp ──────────────────────────────────────────────────── */
  whatsapp: [
    {
      name: 'Mensaje entrante → ficha y respuesta de acuse',
      goal: 'Que ningún mensaje de cliente se pierda en el teléfono de nadie.',
      difficulty: 'intermedia',
      platform: 'n8n · webhook de WhatsApp Business (Cloud API)',
      trigger: 'La Cloud API manda un webhook a tu n8n con cada mensaje recibido en el número de empresa.',
      steps: [
        'Verificar la firma del webhook y responder 200 al instante: si tardas, Meta reintenta y llegan duplicados.',
        'Extraer remitente, texto y tipo (texto, audio, imagen) del payload.',
        'Comprobar si el remitente ya tiene conversación abierta (por teléfono) antes de crear ficha nueva.',
        'Guardar el mensaje en tu registro (hoja o base de datos) con marca de tiempo.',
        'Responder el acuse dentro de la ventana de 24 horas: fuera de ella solo se permiten plantillas aprobadas.',
        'Avisar al equipo si el mensaje contiene palabras de urgencia definidas por ti.',
      ],
      test: 'Escribe desde un móvil de prueba: mensaje normal, audio y dos mensajes seguidos. Comprueba que el segundo no crea segunda ficha.',
      failure: 'Si dejan de llegar webhooks, el token caducó o Meta desactivó la URL por errores: revisa el panel de la app en developers.facebook.com. Los reintentos de Meta son la causa número uno de duplicados.',
      credentials: 'App de WhatsApp Business en Meta for Developers, token permanente, número verificado y la Production URL del webhook. La ventana de 24 horas es regla de Meta, no tuya.',
    },
    {
      name: 'Aviso saliente con plantilla cuando pasa algo en tu sistema',
      goal: 'Confirmaciones y avisos (pedido listo, cita mañana) al WhatsApp del cliente.',
      difficulty: 'intermedia',
      platform: 'n8n · nodo de WhatsApp / HTTP a la Cloud API',
      trigger: 'Lo que ocurra en tu sistema: fila nueva, cambio de estado, hora programada.',
      steps: [
        'Comprobar que hay consentimiento registrado para escribir a ese número: sin él, no se envía.',
        'Elegir la plantilla aprobada que toque (los mensajes libres solo valen dentro de la ventana de 24 h).',
        'Rellenar las variables de la plantilla con los datos del caso.',
        'Enviar y guardar el identificador del mensaje que devuelve la API.',
        'Escuchar el webhook de estado (enviado, entregado, leído, fallido) y apuntar el resultado.',
        'Si falla por número inválido, marcar la ficha para revisión en vez de reintentar a ciegas.',
      ],
      test: 'Envía a tu propio número una plantilla real. Comprueba que el estado llega a «entregado» en tu registro.',
      failure: 'Error 131047: fuera de la ventana de 24 h sin plantilla. Error 100 con variables: la plantilla espera otro número de parámetros. Las plantillas se aprueban en el panel de Meta y tardan horas.',
      credentials: 'Las mismas de la app de Meta, más las plantillas aprobadas. El consentimiento es obligación legal (RGPD), no cortesía.',
    },
    {
      name: 'Recordatorio de cita 24 horas antes',
      goal: 'Bajar los plantones: recordatorio automático con opción de confirmar o cambiar.',
      difficulty: 'intermedia',
      platform: 'n8n · Schedule + Cloud API + tu agenda',
      trigger: 'Schedule cada hora, que busca citas de mañana aún sin recordatorio enviado.',
      steps: [
        'Leer de tu agenda (hoja, Calendar, base de datos) las citas entre 23 y 25 horas vista.',
        'Descartar las que ya tienen recordatorio enviado (columna de control).',
        'Enviar la plantilla con fecha, hora y los botones de confirmar o cambiar.',
        'Marcar el envío en la columna de control con fecha y hora.',
        'Escuchar las respuestas de los botones y actualizar la cita: confirmada o a recolocar.',
        'Avisar al equipo de las que pidieron cambio.',
      ],
      test: 'Crea una cita de prueba para mañana con tu número. Debe llegar un solo recordatorio aunque el flujo corra cada hora.',
      failure: 'Recordatorios duplicados = falta la columna de control o se lee antes de escribir. Respuestas perdidas = el webhook de entrada no distingue respuestas de botón de mensajes normales: mira el campo type del payload.',
      credentials: 'Plantilla con botones aprobada por Meta. Los botones de respuesta rápida llegan como payload distinto al texto: pruébalo antes de darlo por hecho.',
    },
    {
      name: 'Audio de WhatsApp → texto → resumen en tu registro',
      goal: 'Que los audios de tres minutos de los clientes se conviertan en texto accionable.',
      difficulty: 'avanzada',
      platform: 'n8n · Cloud API + transcripción + modelo de lenguaje',
      trigger: 'Webhook de mensaje entrante con type audio.',
      steps: [
        'Descargar el audio con la URL temporal que da la API (caduca: descárgalo al momento).',
        'Transcribir con un servicio de voz a texto (Whisper u otro).',
        'Resumir con el modelo: qué pide, para cuándo, y si hay urgencia, en salida estructurada.',
        'Guardar transcripción y resumen en la ficha del cliente.',
        'Responder el acuse y avisar al equipo con el resumen, no con el audio.',
      ],
      test: 'Mándate un audio real con un encargo dentro. El resumen debe capturar qué se pide y para cuándo; si no, ajusta el prompt.',
      failure: 'Si la descarga da 404, la URL caducó: hay que descargar en el mismo flujo, no en uno posterior. Coste: transcribir + resumir cuesta céntimos por audio; ponle contador mensual.',
      credentials: 'Meta + clave del servicio de transcripción y del modelo, con topes de gasto. Los audios son datos personales: borra el archivo tras transcribir si no lo necesitas.',
    },
    {
      name: 'Escalado a humano cuando el bot no llega',
      goal: 'Que la automatización sepa retirarse: casos complejos o cliente enfadado pasan a una persona.',
      difficulty: 'avanzada',
      platform: 'n8n · Cloud API + clasificador',
      trigger: 'Cada mensaje entrante, tras el flujo de ficha.',
      steps: [
        'Clasificar el mensaje: consulta simple, gestión, queja, urgencia.',
        'Las simples responde el flujo con respuestas definidas por ti (horario, dirección, precios).',
        'Queja o urgencia: marcar la conversación como «humana», avisar al responsable con el historial reciente, y que el bot DEJE de responder en esa conversación.',
        'Guardar el estado humana/bot por conversación para que el flujo lo respete.',
        'Volver a modo bot solo cuando el humano cierre la conversación.',
      ],
      test: 'Escribe «quiero poner una reclamación»: debe avisar al responsable y el bot debe callar en los mensajes siguientes.',
      failure: 'El fallo grave es el bot respondiendo a un cliente enfadado en bucle. El estado por conversación es lo que lo impide: sin él, no actives este flujo.',
      credentials: 'Las de Meta más el registro de estado por conversación. Regla de la casa: en la duda, escala; un humano de más es barato, un cliente perdido no.',
    },
  ],

  /* ── Slack ─────────────────────────────────────────────────────── */
  slack: [
    {
      name: 'Avisos de tus sistemas en el canal correcto',
      goal: 'Que lo que pasa en tus flujos (altas, errores, umbrales) llegue a Slack ordenado y sin ruido.',
      difficulty: 'basica',
      platform: 'n8n · nodo de Slack',
      trigger: 'Lo que tus otros flujos decidan: alta nueva, error, umbral cruzado.',
      steps: [
        'Crear la app de Slack con permiso chat:write e invitarla a los canales con /invite.',
        'Separar canales: #avisos-negocio para lo normal, #alertas-fallos para lo roto.',
        'Primera línea del mensaje con el dato clave: es lo único que se ve en el móvil.',
        'Detalle en el hilo, no en el canal: un aviso, un mensaje.',
        'Los éxitos van agrupados en un resumen diario; los fallos, al momento.',
      ],
      test: 'Manda un aviso de prueba y míralo en el móvil bloqueado: si la notificación no dice qué pasó, reescribe la primera línea.',
      failure: 'not_in_channel: falta el /invite. channel_not_found: usa el ID del canal (C0...), no el nombre. Un canal que abusa de avisos acaba silenciado y entonces no existe.',
      credentials: 'App de Slack con token de bot (xoxb-...). Los webhooks entrantes valen para empezar; la app da más control.',
    },
    {
      name: 'Reacción con emoji → acción real',
      goal: 'Convertir Slack en botonera: un ✅ del responsable aprueba; un 📌 crea tarea.',
      difficulty: 'intermedia',
      platform: 'n8n · Slack Trigger (reaction_added)',
      trigger: 'Evento reaction_added en los canales donde está la app.',
      steps: [
        'Escuchar el evento y filtrar por emoji concreto y por canal.',
        'Comprobar QUIÉN reaccionó: las aprobaciones solo valen de la lista de aprobadores.',
        'Recuperar el mensaje original para sacar el caso al que se refiere.',
        'Ejecutar la acción: aprobar el registro, crear la tarea, mover el estado.',
        'Responder en el hilo con confirmación de qué se hizo y quién lo aprobó.',
        'Ignorar en silencio las reacciones de quien no está autorizado.',
      ],
      test: 'Reacciona con ✅ desde una cuenta autorizada y desde otra que no: solo la primera debe ejecutar, y el hilo debe decir quién aprobó.',
      failure: 'Si la acción se ejecuta dos veces, alguien quitó y volvió a poner el emoji: guarda el estado aprobado y haz la acción idempotente (segunda aprobación = no hacer nada).',
      credentials: 'App con reactions:read, channels:history y chat:write, y suscripción a eventos apuntando a tu webhook de n8n.',
    },
    {
      name: 'Comando /consulta para preguntar a tus datos desde Slack',
      goal: 'Que el equipo consulte el estado de un pedido o cliente sin salir de Slack ni tocar la base de datos.',
      difficulty: 'avanzada',
      platform: 'n8n · Slash command + tu base de datos',
      trigger: 'El comando /consulta [término] definido en la app de Slack, que llama a tu webhook.',
      steps: [
        'Responder a Slack en menos de 3 segundos con «buscando…» (obligatorio: si no, error de timeout).',
        'Buscar el término en tu base o tu hoja: por nombre, correo o número de pedido.',
        'Formatear la ficha encontrada con los cuatro datos útiles y el enlace al sistema.',
        'Mandar el resultado con la response_url que Slack incluyó en la llamada.',
        'Si no hay resultados, decirlo con sugerencia («prueba con el correo»), no en silencio.',
      ],
      test: 'Lanza /consulta con un cliente real, uno inexistente y un término ambiguo con varios resultados: los tres deben responder algo útil.',
      failure: 'timeout de 3 segundos: la respuesta inmediata es OBLIGATORIA y la búsqueda va después, con response_url. Es el error que todo el mundo comete la primera vez.',
      credentials: 'App con el slash command configurado hacia tu Production URL, más acceso de lectura a tus datos. Cuidado con qué datos personales enseñas en un canal: mejor por mensaje directo.',
    },
    {
      name: 'Resumen diario del canal de soporte con IA',
      goal: 'Un párrafo cada tarde: qué se preguntó hoy, qué quedó sin responder, qué se repite.',
      difficulty: 'intermedia',
      platform: 'n8n · Schedule + Slack + modelo de lenguaje',
      trigger: 'Schedule a las 18:00 de lunes a viernes.',
      steps: [
        'Leer los mensajes del día del canal con channels:history.',
        'Filtrar bots y avisos automáticos: solo mensajes de personas.',
        'Pedir al modelo el resumen: temas, preguntas sin respuesta (sin respuestas en hilo), y repetidas de la semana.',
        'Publicar el resumen en el canal del equipo con los enlaces a los mensajes sin responder.',
      ],
      test: 'Ejecútalo un día con movimiento real: las «sin respuesta» deben ser mensajes de verdad sin hilo, compruébalo a mano la primera semana.',
      failure: 'Si el resumen inventa temas, baja la temperatura y limita al modelo a los mensajes dados («solo con estos mensajes, no añadas nada»). Si faltan mensajes, la app no está en el canal o falta el permiso de historial.',
      credentials: 'App con channels:history y chat:write + clave del modelo con tope. Los mensajes del equipo son datos internos: usa un proveedor aprobado por tu empresa.',
    },
    {
      name: 'Alta de empleado → carpeta, accesos y bienvenida',
      goal: 'Que el primer día de alguien no dependa de que nadie se acuerde de nada.',
      difficulty: 'intermedia',
      platform: 'n8n · disparo desde el alta + Slack',
      trigger: 'Fila nueva en la hoja de altas de personal (o el evento de tu sistema de RRHH).',
      steps: [
        'Crear la carpeta del empleado en Drive con la estructura estándar.',
        'Invitarle a los canales de Slack que tocan según su equipo.',
        'Mandarle el mensaje de bienvenida con los enlaces de los primeros días.',
        'Crear la lista de tareas del responsable (material, accesos que sí requieren humano).',
        'Avisar en el canal del equipo de que se incorpora, con fecha.',
      ],
      test: 'Da de alta a una persona ficticia con tu correo: revisa carpeta, canales y mensaje. Bórralo todo después.',
      failure: 'Los permisos de verdad (correo corporativo, sistemas internos) NO se automatizan desde aquí sin visto bueno de IT: el flujo crea la petición, no el acceso.',
      credentials: 'Slack con users:write limitado, Google Drive, y acuerdo explícito con IT de qué puede tocar este flujo.',
    },
  ],

  /* ── GitHub ────────────────────────────────────────────────────── */
  github: [
    {
      name: 'Push a main → desplegar y avisar con el resultado',
      goal: 'Que publicar sea consecuencia de subir código, con aviso de si salió bien o mal.',
      difficulty: 'basica',
      platform: 'GitHub Actions (nativo) + aviso a Slack/Telegram',
      trigger: 'on: push a la rama main del repositorio.',
      steps: [
        'Workflow de Actions: instalar dependencias, correr las pruebas, construir.',
        'Si las pruebas fallan, parar ahí: no se despliega nada roto.',
        'Desplegar (Vercel, servidor propio) solo con pruebas en verde.',
        'Avisar al canal con commit, autor y enlace, tanto en éxito como en fallo.',
        'En fallo, incluir las últimas líneas del log: el aviso debe bastar para empezar a arreglar.',
      ],
      test: 'Sube un commit que rompa una prueba a propósito: debe parar, no desplegar y avisar con el motivo.',
      failure: 'Si el despliegue va aunque fallen pruebas, falta el needs: entre jobs. Si Actions no arranca, el YAML tiene un error de indentación: el validador del propio GitHub lo señala.',
      credentials: 'Los secretos del despliegue en Settings → Secrets del repo, nunca en el YAML. El aviso usa un webhook del canal.',
    },
    {
      name: 'Issue nueva → clasificar, etiquetar y asignar',
      goal: 'Que las issues no se acumulen sin dueño ni etiqueta.',
      difficulty: 'intermedia',
      platform: 'n8n · GitHub Trigger (issues) + modelo de lenguaje',
      trigger: 'Webhook de GitHub al abrirse una issue en el repo.',
      steps: [
        'Recibir el webhook con título y cuerpo de la issue.',
        'Clasificar con el modelo: bug, mejora, pregunta o duplicada, contra la lista de issues abiertas.',
        'Poner la etiqueta y asignar según el área (rutas de archivos citadas, palabras clave).',
        'Si parece duplicada, comentar con el enlace a la original y etiquetar «posible duplicada» — cerrar lo decide un humano.',
        'Si es de un cliente de pago (autor en tu lista), avisar al canal con prioridad.',
      ],
      test: 'Abre una issue de prueba clara y una ambigua: la ambigua debe quedar «sin clasificar» para revisión, no mal etiquetada con confianza.',
      failure: 'Cerrar duplicadas automáticamente es la línea que no se cruza: el modelo se equivoca y cerrarle una issue válida a alguien es caro. Etiquetar y sugerir, sí; cerrar, humano.',
      credentials: 'Webhook del repo (Settings → Webhooks) hacia tu Production URL + token de GitHub con permiso de issues + clave del modelo.',
    },
    {
      name: 'Pull request → resumen del cambio para no técnicos',
      goal: 'Que negocio sepa qué se está cambiando sin leer código.',
      difficulty: 'intermedia',
      platform: 'n8n · GitHub Trigger (pull_request) + modelo',
      trigger: 'PR abierta o marcada lista para revisar.',
      steps: [
        'Recoger título, descripción y la lista de archivos cambiados (el diff completo solo si es pequeño).',
        'Pedir al modelo el resumen en castellano de negocio: qué cambia para el usuario, qué riesgo tiene, qué conviene probar.',
        'Publicar el resumen como comentario en la PR.',
        'Mandar la versión de una línea al canal de producto.',
      ],
      test: 'Ábrelo con una PR real pequeña: el resumen debe entenderlo alguien que no programa. Si habla de archivos y funciones, ajusta el prompt.',
      failure: 'Con PRs enormes el diff no cabe en el contexto: resume por la lista de archivos y el título, y dilo en el comentario («resumen parcial: cambio grande»).',
      credentials: 'Webhook de PRs + token con permiso de comentar + clave del modelo. El código puede ser confidencial: usa un proveedor que no entrene con tus datos.',
    },
    {
      name: 'Aviso de dependencia con vulnerabilidad conocida',
      goal: 'Enterarte de los avisos de seguridad de tus dependencias sin vivir en GitHub.',
      difficulty: 'basica',
      platform: 'GitHub (Dependabot nativo) + n8n para el aviso',
      trigger: 'Alerta de Dependabot en cualquiera de tus repos.',
      steps: [
        'Activar Dependabot alerts en los repos (Settings → Security).',
        'Webhook de la organización o repo hacia n8n filtrando eventos de seguridad.',
        'Clasificar por severidad: críticas y altas avisan al momento; el resto, al resumen semanal.',
        'El aviso lleva paquete, versión arreglada y enlace: lo que hace falta para decidir.',
      ],
      test: 'Los repos con dependencias viejas generan alertas reales enseguida; comprueba que la severidad separa bien el ruido de lo urgente.',
      failure: 'El error clásico es el contrario: activar el aviso de TODO y silenciarlo a la semana. Críticas al canal, el resto al viernes.',
      credentials: 'Permisos de administración del repo para webhooks de seguridad. Dependabot es gratuito en repos públicos y privados.',
    },
    {
      name: 'Release publicada → changelog y aviso a clientes',
      goal: 'Que publicar versión dispare la comunicación, no otra tarea manual.',
      difficulty: 'intermedia',
      platform: 'n8n · GitHub Trigger (release)',
      trigger: 'Evento release published del repositorio.',
      steps: [
        'Recoger el nombre de la versión y las notas de la release.',
        'Reescribir las notas con el modelo en lenguaje de cliente: qué hay nuevo y qué se arregló, sin jerga.',
        'Publicar en el canal interno y en la página de novedades.',
        'Preparar (no enviar) el borrador del correo a clientes: enviar masivo lo aprueba un humano.',
      ],
      test: 'Publica una release de prueba en un repo de prueba: el texto de cliente no debe contener nombres de funciones ni de archivos.',
      failure: 'El borrador que se envía solo, sin aprobación, es la receta del correo masivo con un error dentro. El humano en el último paso no es opcional.',
      credentials: 'Webhook de releases + modelo + acceso al gestor de correo en modo borrador.',
    },
  ],

  /* ── Telegram ──────────────────────────────────────────────────── */
  telegram: [
    {
      name: 'Bot de avisos personales: tu sistema te habla por Telegram',
      goal: 'El canal de avisos más barato y fiable que existe: gratis, instantáneo y sin app corporativa.',
      difficulty: 'basica',
      platform: 'n8n · nodo de Telegram',
      trigger: 'Cualquier flujo tuyo que quiera avisarte.',
      steps: [
        'Crear el bot con @BotFather (/newbot) y guardar el token.',
        'Escribir /start al bot desde tu cuenta y capturar tu chat_id con el Telegram Trigger.',
        'Guardar el chat_id: es tu «dirección» para todos los flujos futuros.',
        'Nodo de Telegram en cualquier flujo: sendMessage con el aviso.',
        'Formato con negritas y emojis funcionales: 🔴 fallo, 🟡 aviso, 🟢 resumen.',
      ],
      test: 'Mándate un aviso desde un flujo de prueba: debe llegar en menos de un segundo.',
      failure: 'chat not found: no has escrito /start al bot (los bots no pueden iniciar conversación, regla de Telegram). 401: token mal copiado.',
      credentials: 'Solo el token de BotFather. Es la integración con mejor relación utilidad/esfuerzo de todo el curso.',
    },
    {
      name: 'Bot de consulta: pregunta a tus datos desde el móvil',
      goal: 'Escribir «pedido 2043» al bot y recibir la ficha, desde cualquier sitio.',
      difficulty: 'intermedia',
      platform: 'n8n · Telegram Trigger + tus datos',
      trigger: 'Mensaje entrante al bot.',
      steps: [
        'Telegram Trigger escuchando mensajes.',
        'Filtrar por chat_id autorizado: el bot es público por diseño y cualquiera puede encontrarlo — la lista blanca es la seguridad.',
        'Interpretar la consulta: patrón simple (número de pedido) o modelo para lenguaje libre.',
        'Buscar en tu hoja o base y responder la ficha formateada.',
        'A los no autorizados, silencio o «bot privado», y registro del intento.',
      ],
      test: 'Pregunta desde tu cuenta y desde otra no autorizada: la segunda no debe recibir datos.',
      failure: 'El olvido de la lista blanca es grave: un bot sin filtro le enseña tus datos a quien lo encuentre. Es la primera línea del flujo, no un extra.',
      credentials: 'Token del bot + acceso de lectura a tus datos. El chat_id autorizado se guarda en el flujo, no en el código.',
    },
    {
      name: 'Aprobar desde el móvil con dos botones',
      goal: 'Aprobaciones (presupuesto, publicación, descuento) sin abrir el portátil.',
      difficulty: 'intermedia',
      platform: 'n8n · Telegram con botones inline + Wait',
      trigger: 'El flujo que necesita aprobación llega a su paso humano.',
      steps: [
        'Enviar el caso al aprobador con dos botones inline: Aprobar / Rechazar.',
        'El flujo espera (nodo Wait con webhook) la pulsación.',
        'Al pulsar, verificar que quien pulsó es el aprobador.',
        'Continuar por la rama que toque y editar el mensaje original con el resultado («Aprobado por Ana, 14:02»).',
        'Si nadie responde en el plazo, recordar una vez y escalar después.',
      ],
      test: 'Lanza una aprobación de prueba y pulsa desde otra cuenta: no debe valer. Deja otra sin responder: debe escalar.',
      failure: 'Si el botón no hace nada, el callback no está llegando al Wait: revisa que la URL del webhook de reanudación sea la production. El mensaje editado con el resultado evita dobles aprobaciones.',
      credentials: 'Token del bot y la lista de aprobadores por chat_id. Deja registro de quién aprobó qué y cuándo: es tu auditoría.',
    },
    {
      name: 'Canal de Telegram como tablón automático',
      goal: 'Publicar novedades (ofertas, avisos, contenido) en tu canal sin hacerlo a mano.',
      difficulty: 'basica',
      platform: 'n8n · Schedule o disparo + Telegram',
      trigger: 'Lo que genere la novedad: fila nueva, RSS, hora fija.',
      steps: [
        'Añadir el bot como administrador del canal con permiso de publicar.',
        'Formatear la publicación con plantilla fija: título, dos líneas, enlace.',
        'Publicar con sendMessage al @nombre_del_canal.',
        'Registrar lo publicado para no repetir contenido.',
      ],
      test: 'Publica una prueba en un canal de prueba primero. Comprueba el formato en móvil.',
      failure: 'CHAT_WRITE_FORBIDDEN: el bot no es administrador del canal. Publicar dos veces lo mismo: falta el registro de publicados.',
      credentials: 'Bot como admin del canal. Un canal es público: nada de datos de clientes ahí.',
    },
  ],

  /* ── Supabase ──────────────────────────────────────────────────── */
  supabase: [
    {
      name: 'Fila insertada → webhook a n8n → el resto del proceso',
      goal: 'Que un alta en tu base (desde tu app) dispare el proceso completo sin tocar la app.',
      difficulty: 'intermedia',
      platform: 'Supabase Database Webhooks → n8n',
      trigger: 'Webhook nativo de Supabase en INSERT sobre la tabla (Database → Webhooks).',
      steps: [
        'Crear el webhook en Supabase: tabla, evento INSERT, y la Production URL de tu n8n.',
        'En n8n, validar el secreto compartido de la cabecera: que nadie pueda inventarse altas.',
        'Leer el registro del payload (viene entero, con la fila nueva).',
        'Hacer lo que siga: correo de bienvenida, ficha en el CRM, aviso al equipo.',
        'Apuntar el resultado en una columna de la propia fila (processed_at) vía API de Supabase.',
      ],
      test: 'Inserta una fila desde el Table Editor: el flujo debe dispararse en un segundo. Inserta otra con datos incompletos y comprueba el camino de error.',
      failure: 'Si no llega, el webhook apunta a la URL de test (muere con el editor cerrado) o el flujo no está activo. Supabase reintenta si respondes error: haz el flujo idempotente con processed_at.',
      credentials: 'Proyecto de Supabase con el webhook, secreto compartido, y la service_role key SOLO en la credencial de n8n, jamás en el navegador.',
    },
    {
      name: 'Tarea programada dentro de Supabase con pg_cron',
      goal: 'Limpiezas y cierres diarios que corren DENTRO de la base, sin depender de nada externo.',
      difficulty: 'avanzada',
      platform: 'Supabase nativo · extensión pg_cron',
      trigger: 'El planificador de la propia base: cada noche a las 3:00.',
      steps: [
        'Activar la extensión pg_cron desde Database → Extensions.',
        'Escribir la operación como función SQL: borrar sesiones caducadas, archivar cerrados, recalcular contadores.',
        "Programarla: select cron.schedule('limpieza', '0 3 * * *', 'select limpieza_nocturna()');",
        'Registrar cada pasada en una tabla de auditoría (cuándo, cuántas filas).',
        'Un flujo de n8n semanal comprueba que la auditoría tiene entradas recientes: el vigilante del vigilante.',
      ],
      test: 'Prográmala cada minuto en pruebas, verifica dos pasadas en la auditoría, y cámbiala a la hora real.',
      failure: 'pg_cron corre aunque tú no mires: sin la tabla de auditoría y su vigilante, puede llevar semanas rota sin que nadie lo sepa.',
      credentials: 'Acceso SQL al proyecto. pg_cron usa la hora UTC del servidor: las 3:00 de Madrid son las 1:00 o las 2:00 UTC según la época.',
    },
    {
      name: 'Usuario nuevo registrado → bienvenida y alta en tu CRM',
      goal: 'Que cada registro en tu app dispare el circuito comercial.',
      difficulty: 'intermedia',
      platform: 'Supabase Auth Hook / webhook sobre auth.users → n8n',
      trigger: 'Alta en la tabla de usuarios de Auth (webhook en INSERT o Auth Hook).',
      steps: [
        'Configurar el disparo sobre el alta de usuario (webhook de base de datos sobre la tabla de perfiles es lo más simple).',
        'Esperar 10 minutos (Wait): los registros que se borran al minuto no merecen circuito.',
        'Comprobar que el usuario sigue existiendo y confirmó el correo.',
        'Crear la ficha en tu CRM u hoja comercial con origen «app».',
        'Enviar la bienvenida (plantilla revisada por un humano una vez, no cada envío).',
      ],
      test: 'Regístrate con un correo de prueba: la ficha y la bienvenida deben llegar tras la espera, y solo si confirmaste el correo.',
      failure: 'Bienvenidas a correos sin confirmar = spam a direcciones equivocadas. La comprobación tras el Wait no es paranoia: es limpieza de datos.',
      credentials: 'Webhook + service_role en n8n. La tabla auth.users es sensible: mejor un espejo en public.profiles y disparar sobre él.',
    },
    {
      name: 'Archivo subido al Storage → procesarlo',
      goal: 'Que subir un PDF o una imagen a tu app dispare su procesamiento (extraer, redimensionar, clasificar).',
      difficulty: 'avanzada',
      platform: 'Supabase Storage webhook → n8n',
      trigger: 'Objeto creado en el bucket de Storage.',
      steps: [
        'Webhook sobre la tabla storage.objects en INSERT, filtrado por bucket.',
        'Descargar el archivo en n8n con URL firmada temporal.',
        'Procesar según el tipo: extraer texto del PDF, miniatura de la imagen, transcripción del audio.',
        'Guardar el resultado en la tabla que corresponda, enlazado al archivo.',
        'Marcar el objeto como procesado en metadatos para no repetir.',
      ],
      test: 'Sube un PDF real desde la app: el texto extraído debe aparecer en su tabla en menos de un minuto.',
      failure: 'Archivos enormes rompen el flujo por memoria o tiempo: pon límite de tamaño en la subida (política del bucket) y trocea el procesamiento pesado.',
      credentials: 'service_role para las URLs firmadas. Los archivos de usuarios son datos personales: procesa y no los muevas a servicios que no toquen.',
    },
    {
      name: 'Copia de seguridad externa semanal de las tablas críticas',
      goal: 'Que tus datos existan también fuera de Supabase, restaurables por ti.',
      difficulty: 'intermedia',
      platform: 'n8n · Schedule + API de Supabase',
      trigger: 'Schedule los domingos a las 23:00.',
      steps: [
        'Exportar las tablas críticas vía API o pg_dump (según acceso) a JSON o CSV.',
        'Comprimir y subir a un almacenamiento ajeno a Supabase (Drive, S3, disco propio).',
        'Verificar la copia: abrirla y contar filas contra la base.',
        'Registrar fecha, tamaño y recuento; avisar solo si falla.',
        'Una vez al trimestre: restaurar la copia en un proyecto vacío. Una copia no probada no es una copia.',
      ],
      test: 'Ejecuta y restaura la copia en un proyecto de prueba: si no sabes restaurarla hoy, no sabrás con el agua al cuello.',
      failure: 'Supabase tiene sus copias, pero son SUYAS y de su plan: la externa te protege de cierres de cuenta, errores propios y cambios de plan. El fallo silencioso se evita con el aviso de «no se hizo».',
      credentials: 'service_role o cadena de conexión de solo lectura. La copia lleva datos personales: cífrala y contrólale el acceso igual que a la base.',
    },
  ],

  /* ── Notion ────────────────────────────────────────────────────── */
  notion: [
    {
      name: 'Elemento nuevo en una base de Notion → circuito completo',
      goal: 'Que añadir una tarjeta en Notion (lead, tarea, pedido) dispare el proceso.',
      difficulty: 'intermedia',
      platform: 'n8n · Notion Trigger (por sondeo)',
      trigger: 'El Notion Trigger pregunta cada minuto por elementos nuevos de la base elegida.',
      steps: [
        'Compartir la base con la integración de Notion: sin ese paso, la API no la ve (es el 404 clásico).',
        'Notion Trigger sobre la base, ordenada por fecha de creación.',
        'Leer las propiedades: en la API cada tipo (título, select, fecha) llega con estructura distinta; mapear con calma una vez.',
        'Ejecutar el proceso: aviso, ficha externa, correo.',
        'Marcar el elemento con una propiedad «procesado» para que el reintento no duplique.',
      ],
      test: 'Crea una tarjeta de prueba: el flujo debe verla en uno o dos minutos (es sondeo, no webhook: el retardo es normal).',
      failure: 'object_not_found: la base no está compartida con la integración. Propiedades vacías: el nombre de la propiedad cambió en Notion y el mapeo quedó viejo.',
      credentials: 'Integración interna de Notion con su token, y la base COMPARTIDA con ella. El retardo de sondeo es el precio: si necesitas segundos, Notion no es el disparador.',
    },
    {
      name: 'Resumen semanal de lo movido en Notion',
      goal: 'Los lunes, un mensaje con lo creado, cerrado y atascado la semana pasada.',
      difficulty: 'basica',
      platform: 'n8n · Schedule + Notion',
      trigger: 'Schedule los lunes a las 8:30.',
      steps: [
        'Consultar la base filtrando por «última edición en los últimos 7 días».',
        'Agrupar por estado: nuevo, cerrado, sin tocar hace más de 14 días (los atascados).',
        'Formatear el resumen con recuentos y los tres atascados más viejos con enlace.',
        'Enviar al canal del equipo.',
      ],
      test: 'Ejecútalo a mano un lunes: los atascados deben ser de verdad los que nadie toca, compruébalo contra la base.',
      failure: 'Si la consulta trae de más, el filtro de fecha usa la zona horaria mal: las fechas de la API de Notion van en ISO con zona; compara en UTC.',
      credentials: 'La misma integración de Notion, solo lectura aquí.',
    },
    {
      name: 'Correo importante → tarjeta en Notion con resumen',
      goal: 'Que los correos que importan acaben como tarjetas accionables, no perdidos en la bandeja.',
      difficulty: 'intermedia',
      platform: 'n8n · Gmail Trigger + modelo + Notion',
      trigger: 'Correo entrante con etiqueta concreta (la pones tú o un filtro de Gmail).',
      steps: [
        'Gmail Trigger filtrado por la etiqueta «a-notion».',
        'Resumir el correo con el modelo: qué se pide, de quién, para cuándo.',
        'Crear la tarjeta en la base de Notion con el resumen, el enlace al hilo y la fecha límite si la hay.',
        'Quitar la etiqueta del correo: la bandeja queda limpia y el flujo no lo reprocesa.',
      ],
      test: 'Etiqueta un correo real: la tarjeta debe aparecer con el resumen correcto y la etiqueta debe desaparecer del correo.',
      failure: 'Si se crean tarjetas dobles, la etiqueta no se quita (permiso modify de Gmail ausente) y el sondeo lo vuelve a ver.',
      credentials: 'Gmail OAuth con permiso de modificar etiquetas + integración de Notion + modelo con tope.',
    },
  ],

  /* ── Airtable ──────────────────────────────────────────────────── */
  airtable: [
    {
      name: 'Registro nuevo → proceso externo con marca de vuelta',
      goal: 'Airtable como panel de control: lo que entra ahí dispara lo de fuera.',
      difficulty: 'basica',
      platform: 'n8n · Airtable Trigger',
      trigger: 'Registro creado en la tabla, detectado por sondeo sobre el campo Created time.',
      steps: [
        'Añadir a la tabla un campo Created time (obligatorio para que el disparador ordene bien).',
        'Airtable Trigger sobre la base y tabla.',
        'Proceso externo: correo, alta en otro sistema, documento generado.',
        'Escribir el resultado en el registro: estado «procesado» y enlace a lo creado.',
      ],
      test: 'Crea un registro de prueba y comprueba el viaje de ida y la marca de vuelta.',
      failure: 'NOT_AUTHORIZED: el token no tiene scope sobre esa base (los tokens de Airtable son por base, no globales). Sin Created time el disparador repite o se salta registros.',
      credentials: 'Personal Access Token de Airtable con la base marcada y scopes de lectura/escritura.',
    },
    {
      name: 'Automatización nativa de Airtable: aviso sin salir de la herramienta',
      goal: 'Para avisos simples, Airtable se basta solo: sin n8n por medio.',
      difficulty: 'basica',
      platform: 'Airtable Automations (nativo)',
      trigger: 'When record matches conditions: el estado cambia a «urgente».',
      steps: [
        'En la pestaña Automations, crear la automatización con el disparador de condición.',
        'Acción: enviar correo o mensaje de Slack con campos del registro.',
        'Probar con el botón de test sobre un registro real.',
        'Activarla y apuntar en tu inventario de automatizaciones que esta vive DENTRO de Airtable.',
      ],
      test: 'Cambia un registro a «urgente»: el aviso debe llegar. Cámbialo dos veces: llega dos veces (así funciona; si molesta, añade condición de fecha).',
      failure: 'El plan gratuito limita las ejecuciones al mes: para volúmenes altos, n8n. Y las automatizaciones nativas repartidas por diez bases sin inventario son las que nadie recuerda cuando algo falla.',
      credentials: 'Ninguna externa: todo dentro de Airtable. Esa es su gracia y su límite.',
    },
    {
      name: 'Sincronizar Airtable con tu hoja o base maestra',
      goal: 'Que Airtable (donde trabaja el equipo) y tu sistema maestro no se desalineen.',
      difficulty: 'avanzada',
      platform: 'n8n · Schedule + Airtable + destino',
      trigger: 'Schedule cada 15 minutos, con campo Last modified time en la tabla.',
      steps: [
        'Leer los registros modificados desde la última pasada (filtro por Last modified).',
        'Compararlos con el destino por identificador único.',
        'Actualizar solo los campos que cambiaron; crear los que no existan.',
        'Guardar la marca de tiempo de la pasada para la siguiente.',
        'Los conflictos (cambiado en ambos lados) no se pisan: se marcan para revisión humana.',
      ],
      test: 'Cambia un registro en cada lado y deja pasar una pasada: el conflicto debe quedar marcado, no resuelto en silencio.',
      failure: 'La sincronización bidireccional automática total es una trampa: sin la regla de conflictos, un lado pisa al otro y nadie sabe qué versión era la buena.',
      credentials: 'Token de Airtable + credencial del destino. El identificador único compartido es la pieza que lo sostiene todo.',
    },
  ],

  /* ── PostgreSQL ────────────────────────────────────────────────── */
  postgres: [
    {
      name: 'Informe diario desde SQL directo al canal',
      goal: 'El dato de negocio de cada mañana sale de la base, no de una exportación manual.',
      difficulty: 'basica',
      platform: 'n8n · Schedule + nodo de Postgres',
      trigger: 'Schedule a las 8:00.',
      steps: [
        'Consulta SQL de solo lectura con los tres números del día (ventas, altas, pendientes).',
        'Comparar con los del mismo día de la semana pasada.',
        'Formatear el mensaje con los números y las flechas de tendencia.',
        'Enviar al canal. Si la consulta falla, avisar del fallo: un informe que no llega en silencio es peor que un error.',
      ],
      test: 'Cuadra los números del informe contra una consulta manual la primera semana.',
      failure: 'Consultas pesadas a las 8:00 compiten con el trabajo real de la base: si tarda, materialízala de madrugada con pg_cron y lee la tabla materializada.',
      credentials: 'Usuario de SOLO lectura para n8n: un flujo de informes jamás necesita escribir, y si un día se equivoca, que no pueda.',
    },
    {
      name: 'Vigilante de anomalías: filas raras, colas creciendo, huecos',
      goal: 'Detectar lo que huele mal antes de que sea un incidente: pedidos sin pagar de hace días, colas que no bajan.',
      difficulty: 'intermedia',
      platform: 'n8n · Schedule + Postgres',
      trigger: 'Schedule cada hora.',
      steps: [
        'Batería de consultas de control, cada una con su umbral: pendientes de más de 48h, tabla de cola por encima de N, huecos de secuencia.',
        'Solo avisan las que cruzan umbral, con el recuento y los tres casos más viejos.',
        'Cada regla lleva su celda de último aviso: máximo un aviso por regla y día.',
        'Registro de cada pasada en una tabla de control.',
      ],
      test: 'Fuerza una anomalía en datos de prueba y comprueba aviso único y registro.',
      failure: 'La tentación es avisar de todo: a la semana el canal está silenciado. Pocas reglas con umbral bien puesto valen más que veinte con umbral nervioso.',
      credentials: 'El mismo usuario de solo lectura. Las consultas de control se documentan: dentro de un año nadie recordará qué vigila cada una.',
    },
    {
      name: 'Mantenimiento nocturno con pg_cron y verificación externa',
      goal: 'Archivado, limpieza y estadísticas cada noche, dentro de la base, con testigo fuera.',
      difficulty: 'avanzada',
      platform: 'pg_cron (nativo) + n8n de vigilante',
      trigger: 'cron.schedule a las 3:00 UTC.',
      steps: [
        'Función SQL con el mantenimiento: mover a histórico, borrar temporales, refrescar vistas materializadas.',
        'Cada operación escribe su recuento en una tabla de auditoría.',
        'Flujo de n8n a las 8:00 que comprueba que la auditoría tiene la entrada de esta noche.',
        'Si no la tiene, aviso: el mantenimiento no corrió y alguien debe mirar.',
      ],
      test: 'Prográmalo cada 5 minutos en pruebas, verifica auditoría, pasa a la hora real y prueba también el camino del vigilante (borra la entrada y espera el aviso).',
      failure: 'El mantenimiento que falla en silencio semanas es el clásico: la base engorda, todo va más lento y nadie sabe por qué. El vigilante externo existe para eso.',
      credentials: 'Acceso de administración para crear la función y el cron; el vigilante, con el usuario de lectura.',
    },
  ],

  /* ── Vercel ────────────────────────────────────────────────────── */
  vercel: [
    {
      name: 'Cron Job de Vercel: tu tarea programada sin servidor',
      goal: 'Tareas periódicas (renovar datos, mandar resúmenes, limpiar) sin mantener ningún servidor.',
      difficulty: 'intermedia',
      platform: 'Vercel Cron Jobs (nativo)',
      trigger: 'La programación declarada en vercel.json: {"crons":[{"path":"/api/tarea","schedule":"0 7 * * *"}]}.',
      steps: [
        'Crear la ruta /api/tarea en tu proyecto con el trabajo dentro.',
        'Protegerla: comprobar la cabecera de autorización con CRON_SECRET, porque la ruta es pública.',
        'Declarar el cron en vercel.json y desplegar.',
        'Verificar en el panel de Vercel (pestaña Crons) que aparece y cuándo corrió.',
        'La tarea escribe su resultado en un registro tuyo: el panel dice que corrió, tu registro dice qué hizo.',
      ],
      test: 'Llama a la ruta a mano con y sin el secreto: sin él debe devolver 401. Espera la primera ejecución real y compruébala en el panel.',
      failure: 'La ruta sin proteger es una tarea que cualquiera puede disparar. Y ojo al límite de duración de las funciones de tu plan: una tarea larga se corta a medias; trocéala.',
      credentials: 'CRON_SECRET como variable de entorno en Vercel. El horario va en UTC.',
    },
    {
      name: 'Deploy Hook: republicar la web cuando cambia el contenido',
      goal: 'Tu web estática se reconstruye sola cuando tocas el contenido en Notion, la hoja o el CMS.',
      difficulty: 'basica',
      platform: 'Vercel Deploy Hooks + n8n',
      trigger: 'El cambio de contenido (detectado por n8n) llama a la URL del Deploy Hook.',
      steps: [
        'Crear el Deploy Hook en Vercel (Settings → Git → Deploy Hooks) y guardar su URL como secreto.',
        'En n8n, detectar el cambio de contenido (Notion Trigger, Sheets Trigger).',
        'Agrupar cambios: esperar 5 minutos de calma antes de llamar, para no reconstruir veinte veces seguidas.',
        'Llamar al hook y esperar el webhook de deployment succeeded/failed de Vercel.',
        'Avisar solo si falló.',
      ],
      test: 'Cambia el contenido y comprueba que la web nueva aparece en unos minutos. Haz cinco cambios seguidos: debe haber UNA reconstrucción.',
      failure: 'Sin la espera de calma, cada tecla del editor dispara un build: se agota la cuota de builds y los despliegues se pisan.',
      credentials: 'La URL del hook es un secreto: quien la tenga puede desplegarte. Guárdala como credencial, no en el flujo a la vista.',
    },
    {
      name: 'Despliegue fallido → aviso con el motivo masticado',
      goal: 'Enterarte de un build roto al minuto, con el error resumido, no descubrirlo por un cliente.',
      difficulty: 'intermedia',
      platform: 'Vercel webhooks → n8n + modelo',
      trigger: 'Webhook de Vercel en deployment.failed (o deployment.succeeded para el silencio verde).',
      steps: [
        'Configurar el webhook del proyecto hacia n8n.',
        'En fallo: recuperar el log del build por la API de Vercel.',
        'Resumir con el modelo las últimas líneas: qué falló en una frase de castellano.',
        'Avisar con commit, autor, la frase y el enlace al log completo.',
      ],
      test: 'Rompe el build a propósito en una rama: el aviso debe llegar con la causa entendible («falta la variable X», «error de tipos en Y»).',
      failure: 'La mitad de los builds rotos en Vercel son variables de entorno que faltan: si el resumen dice eso, el arreglo es Settings → Environment Variables y redeploy, no tocar código.',
      credentials: 'Webhook del proyecto + token de la API de Vercel para leer logs + modelo con tope.',
    },
  ],

  /* ── Gmail ─────────────────────────────────────────────────────── */
  gmail: [
    {
      name: 'Correo con factura → datos extraídos → contabilidad',
      goal: 'Que las facturas que llegan por correo acaben registradas sin que nadie las copie a mano.',
      difficulty: 'intermedia',
      platform: 'n8n · Gmail Trigger + modelo de lenguaje',
      trigger: 'Correo entrante con adjunto PDF y asunto o remitente de proveedor.',
      steps: [
        'Gmail Trigger filtrado: has:attachment y la etiqueta «facturas» (la pone un filtro de Gmail por remitente).',
        'Descargar el adjunto y extraer el texto del PDF.',
        'Extraer con el modelo, en salida estructurada: proveedor, número, fecha, base, IVA y total.',
        'Validar: el total tiene que cuadrar con base más IVA; si no cuadra, a revisión humana, no al registro.',
        'Registrar la fila en tu hoja o sistema contable, con enlace al correo original.',
        'Etiquetar el correo como «facturas/registrada» para no reprocesarlo.',
      ],
      test: 'Reenvíate tres facturas reales de proveedores distintos: los totales deben cuadrar y la ambigua debe caer en revisión.',
      failure: 'Un dato fiscal mal extraído y registrado en silencio es un problema de verdad: la validación aritmética es la red, y lo que no cuadra JAMÁS entra solo.',
      credentials: 'Gmail OAuth con permiso de lectura y de modificar etiquetas + modelo con tope. Las facturas llevan datos fiscales: proveedor de IA que no entrene con tus datos.',
    },
    {
      name: 'Bandeja clasificada sola: etiquetas por tipo al llegar',
      goal: 'Que el correo llegue preclasificado (cliente, proveedor, urgente, ruido) y la bandeja sea una lista de trabajo.',
      difficulty: 'intermedia',
      platform: 'n8n · Gmail Trigger + modelo',
      trigger: 'Todo correo entrante que no venga ya etiquetado por los filtros nativos.',
      steps: [
        'Lo barato primero: filtros nativos de Gmail por remitente y asunto para lo obvio (newsletters, avisos automáticos).',
        'Lo ambiguo, al modelo: clasificar en las cuatro o cinco categorías TUYAS, con lista cerrada.',
        'Aplicar la etiqueta y, para «urgente», estrella y aviso por Telegram.',
        'Registro diario de recuentos por categoría para ver si la clasificación se sostiene.',
      ],
      test: 'Un día entero en paralelo: el flujo etiqueta pero tú revisas. Si acierta menos de 9 de 10, ajusta las categorías antes de fiarte.',
      failure: 'La clasificación de correo se paga por mensaje: los filtros nativos gratis deben comerse el 70% antes de que el modelo toque nada. Sin eso, la factura de IA crece con tu spam.',
      credentials: 'Gmail OAuth + modelo con tope de gasto. Tus correos son datos sensibles: decide conscientemente qué proveedor los lee.',
    },
    {
      name: 'Respuesta pendiente → recordatorio si nadie contestó en 48 h',
      goal: 'Que ningún correo importante enviado quede sin respuesta y sin seguimiento.',
      difficulty: 'intermedia',
      platform: 'n8n · Schedule + búsqueda de Gmail',
      trigger: 'Schedule diario a las 9:30.',
      steps: [
        'Buscar con la sintaxis de Gmail: enviados con etiqueta «seguimiento» de hace más de 48 h.',
        'Comprobar si el hilo tiene respuesta posterior a tu último mensaje.',
        'Si no la tiene, crear el borrador de recordatorio (no enviarlo: lo revisas y lo mandas tú).',
        'Avisarte con la lista de pendientes y sus borradores listos.',
        'Quitar la etiqueta cuando el hilo tenga respuesta.',
      ],
      test: 'Etiqueta un enviado de hace tres días sin respuesta: mañana debe aparecer el borrador y el aviso.',
      failure: 'El recordatorio que se envía solo acaba mandando presión a quien ya contestó por otro canal: por eso borrador y humano. La automatización prepara; tú decides.',
      credentials: 'Gmail OAuth con permiso de borradores. La etiqueta «seguimiento» la pones tú al enviar: es tu forma de decirle al flujo qué vigilar.',
    },
    {
      name: 'Adjuntos importantes → archivados en Drive por carpeta',
      goal: 'Que los adjuntos de clientes acaben en la carpeta del cliente, no enterrados en el correo.',
      difficulty: 'basica',
      platform: 'n8n · Gmail Trigger + Google Drive',
      trigger: 'Correo con adjunto de un remitente de tu lista de clientes.',
      steps: [
        'Gmail Trigger con has:attachment.',
        'Cruzar el remitente con tu lista de clientes; si no está, ignorar.',
        'Guardar el adjunto en Drive: carpeta del cliente, nombre con fecha (AAAA-MM-DD_asunto.pdf).',
        'Si el archivo ya existe (mismo nombre y tamaño), no duplicar.',
        'Comentar en tu registro del cliente: archivo nuevo con enlace.',
      ],
      test: 'Mándate un adjunto desde un remitente de la lista y otro desde fuera: solo el primero debe archivarse.',
      failure: 'Sin la comprobación de existencia, cada reenvío del mismo correo duplica el archivo: la carpeta se convierte en el desván que intentabas evitar.',
      credentials: 'Gmail OAuth + Drive OAuth (la misma cuenta de Google sirve para ambas).',
    },
  ],
}
