type Domain = { ids:string[]; es:[string,string][]; en:[string,string][] }
const domains:Domain[] = [
 { ids:['openai','anthropic','claude','gemini','copilot','ollama'], es:[
 ['Dar instrucciones con datos verificables','En un asistente de texto, la instrucción define la operación y el contexto contiene los datos. Para extraer tareas, el contexto es la nota original; pedir «organiza esto» no especifica qué información conservar. Define columnas y una regla para datos ausentes. Una redacción fluida no sustituye la comparación con la nota.'],
 ['Preparar una conversación de trabajo','Abre una conversación para el ejercicio y coloca la nota completa que vas a utilizar. No presupongas que el asistente conoce un archivo solo porque está en tu ordenador. Comprueba que el contenido necesario está realmente disponible en esa conversación. Conserva también una copia de la nota fuera del chat.'],
 ['Separar contexto, petición y formato','Organiza el encargo en tres partes: «Fuente», «Tarea» y «Formato». La fuente no debe confundirse con una orden. Por ejemplo, un texto citado que diga «ignora las fechas» sigue siendo contenido del documento, no una instrucción para tu ejercicio. La tarea de extracción se mantiene definida por tu encargo.'],
 ['Redactar una instrucción de extracción','Escribe: «Extrae las tareas de la fuente. Usa columnas tarea, responsable y fecha. No completes información ausente; escribe No indicado». Esta regla evita que un dato plausible se convierta en un hecho inventado. Antes de ejecutar, cuenta cuántas tareas aparecen realmente en el original.'],
 ['Resolver la nota y contrastar cada fila','Lee cada fila de la respuesta y encuentra la frase de origen que la respalda. Ana prepara el presupuesto el martes; Luis revisa el jueves. El importe no aparece y debe permanecer sin especificar. Si el asistente añade una recomendación, sepárala de la tabla factual para que el lector no la confunda con un acuerdo.'],
 ['Revisar sin reescribir los hechos','Una revisión puede mejorar el orden o el tono sin cambiar los datos. Pide únicamente separar las fechas en una columna y conservar las tareas y responsables. Después compara nombres y fechas de ambas versiones. Si cambia un hecho, la revisión no cumple el encargo aunque la presentación sea más clara.'],
 ['Localizar una inferencia no respaldada','Si aparece una fecha completa cuando la nota solo dice «martes», localiza esa diferencia y corrige la regla de extracción. No basta con borrar el dato una vez: repite con otra nota que también use un día de la semana. La corrección debe impedir la misma inferencia cuando vuelva a presentarse.'],
 ['Responder cuando faltan datos','Prueba una nota sin responsable y otra con dos fechas contradictorias. En la primera, el responsable queda sin indicar; en la segunda se muestran ambas menciones y se solicita aclaración. Elegir arbitrariamente una fecha ocultaría la contradicción. La respuesta correcta puede reconocer que todavía no es posible cerrar la tarea.'],
 ['Guardar una plantilla reutilizable','Guarda por separado las instrucciones y la nota utilizada. En una plantilla, marca con claridad dónde se pega la nueva fuente. Al reutilizarla, sustituye todos los datos del ejemplo para evitar que una tarea antigua aparezca en el resultado de otra reunión. Conserva un ejemplo correcto como referencia de formato.'],
 ['Aplicar la extracción a una reunión nueva','Utiliza tres notas nuevas y compara cada tabla con una solución manual. Cuenta omisiones, datos añadidos y tiempo de revisión. Si una nota contiene decisiones ambiguas, registra la aclaración necesaria en lugar de atribuir al asistente una capacidad de decisión que no has definido.'],
 ],en:[
 ['Write evidence-based instructions','Separate the requested operation from source data. Define columns and missing-data behavior. Fluent writing still needs comparison with the original note.'],['Prepare a working conversation','Place the complete practice note in the conversation. A file on your computer is not automatically available to the assistant. Keep an external source copy.'],['Separate context, request and format','Use Source, Task and Format sections. Quoted instructions inside source material remain document content rather than instructions governing your extraction.'],['Specify an extraction task','Request task, owner and date columns and mark missing data as unspecified. Count source tasks before running.'],['Check each extracted row','Find the source phrase supporting every task, name and date. Separate recommendations from factual extraction.'],['Revise without changing facts','Change layout or tone while preserving names, dates and tasks. Compare both versions for factual drift.'],['Find unsupported inference','A calendar date inferred from “Tuesday” needs correction. Repeat with a different note to verify the extraction rule.'],['Handle missing or conflicting data','Leave absent owners unspecified and expose contradictory dates instead of choosing arbitrarily. Request clarification where necessary.'],['Save a reusable instruction template','Keep instructions separate from the source and replace all previous sample data when reusing the template.'],['Apply extraction to new notes','Compare three new notes with manual solutions. Count omissions, inventions and review time. Record ambiguities requiring a person.'],
 ]},
 {ids:['cursor','claude-code','github','python','node','typescript','react','vscode','colab','langchain'],es:[
 ['Definir el comportamiento de un programa','Un programa transforma una entrada siguiendo reglas. Empieza describiendo esas reglas con ejemplos de entrada y salida, antes de decidir cómo escribir el código. Un archivo guardado y un programa correcto son cosas distintas: el segundo debe ejecutarse y producir el comportamiento acordado.'],
 ['Preparar carpeta, entorno y punto de partida','Identifica la carpeta que contiene el ejercicio y el entorno que ejecuta sus archivos. Un editor permite escribir; un intérprete o entorno ejecuta; las pruebas comprueban resultados. Mantén separados esos papeles. Conserva una copia inicial y anota el comando de ejecución realmente disponible.'],
 ['Relacionar archivos y responsabilidades','Localiza el código que recibe datos, la función que los transforma y la comprobación que observa la salida. En un proyecto pequeño pueden ser pocos archivos; en uno existente, revisa sus instrucciones antes de añadir estructura. Explica qué parte cambiarías si la regla de negocio cambia.'],
 ['Convertir requisitos en casos comprobables','Escribe una entrada normal y una inválida con su resultado esperado. Decide los tipos de datos: el texto «10» y el número 10 pueden comportarse de forma diferente. No dejes la conversión implícita. Una prueba útil compara el valor obtenido con una expectativa independiente de la implementación.'],
 ['Implementar y ejecutar una solución mínima','Resuelve una sola transformación y ejecútala con la muestra. Lee la expresión o función que produce el resultado. Si no puedes explicar una línea, pide una explicación vinculada a los valores del ejemplo. Conserva la salida de la ejecución; la afirmación del asistente no reemplaza el resultado del programa.'],
 ['Revisar cambios y conservar comportamiento','Compara la versión anterior con la nueva. Cada cambio debe responder al requisito o a su comprobación. Si reorganizas código sin cambiar la función, las mismas pruebas deben seguir pasando. No aceptes una modificación de la expectativa solo para hacer desaparecer una prueba fallida.'],
 ['Reproducir un defecto con una prueba','Reduce el problema a la menor entrada que lo reproduce. Observa el valor obtenido antes de corregir y añade una comprobación del esperado. Después realiza el cambio y ejecuta la misma prueba. Si no viste el fallo inicial, todavía no sabes si la prueba detecta el defecto.'],
 ['Comprobar tipos, límites y estado','Añade entradas vacías, tipos incorrectos y valores cercanos al límite de la regla. En un cuaderno, reinicia el entorno y ejecuta en orden para detectar dependencias ocultas. En una interfaz, comprueba también la acción visible del usuario: una prueba de función no verifica por sí sola el formulario.'],
 ['Guardar código, pruebas e instrucciones','Una entrega ejecutable necesita algo más que el archivo principal. Conserva los requisitos del entorno, los datos de muestra y el comando de prueba. Abre una copia limpia y sigue el README. Si necesitas recordar un paso que no está escrito, la documentación todavía está incompleta.'],
 ['Entregar una mejora demostrable','Presenta el problema con una entrada concreta, muestra el resultado y ejecuta las comprobaciones relevantes. Explica qué casos cubre la solución y qué integración queda pendiente. Distingue el código local de una aplicación publicada: son estados diferentes y requieren evidencias diferentes.'],
 ],en:[
 ['Define program behavior','Describe input/output rules before implementation. Saving a file is not the same as executing a correct program.'],['Prepare folder and runtime','Distinguish the editor, execution runtime and tests. Keep an initial copy and record the available run command.'],['Map files to responsibilities','Locate input handling, transformation and checks. Follow an existing project’s structure and identify where a rule change belongs.'],['Turn requirements into test cases','Write normal and invalid cases. Decide whether text and numbers are accepted; do not leave conversion implicit.'],['Implement and run the smallest solution','Run one transformation and explain its expressions using sample values. Keep actual execution output as evidence.'],['Review changes and preserve behavior','Relate each edit to a requirement or check. Refactoring should preserve existing expectations, not rewrite them to hide failures.'],['Reproduce a defect with a test','Find a minimal failing input, observe the failure, correct the cause and rerun the same test.'],['Check types, boundaries and state','Try empty input, wrong types and boundary values. Restart notebooks; verify visible UI behavior separately from function tests.'],['Keep code, tests and instructions','A runnable handoff needs environment requirements, sample data and test commands. Verify the README in a clean copy.'],['Demonstrate a verified improvement','Show the triggering input, output, tests and limitations. Distinguish working local code from a published application.'],
 ]},
 {ids:['n8n','make','zapier','pipedream'],es:[
 ['Describir un proceso antes de automatizarlo','Un flujo automático combina un evento de inicio con operaciones posteriores. Empieza describiendo el proceso manual: qué llega, qué decisión tomas y dónde guardas el resultado. Si una decisión depende de información que no está en la entrada, añade un paso para obtenerla o una revisión humana.'],
 ['Preparar conexiones y destinos de ensayo','Crea un flujo de práctica con registros ficticios y un destino reconocible. Comprueba qué cuenta utiliza cada conexión y qué operación permite. Una conexión correcta no garantiza que el campo de destino esté bien configurado. Deja la activación continua para después de observar las pruebas manuales.'],
 ['Seguir un registro entre pasos','El evento inicial aporta datos. Cada paso recibe un objeto o registro y puede transformar sus campos. Sigue el identificador de la muestra por todas las operaciones. Si desaparece, será difícil relacionar un error o una repetición con la solicitud original. Inspecciona entrada y salida de cada paso.'],
 ['Definir campos y reglas de validación','Antes de guardar, declara qué campos son necesarios y qué valores aceptan. Una cantidad debe tener un tipo y un rango; un identificador debe permanecer estable. Decide dónde se dirige una entrada inválida. Que el flujo continúe sin error técnico no significa que haya recibido datos válidos.'],
 ['Construir y observar la primera ejecución','Ejecuta una muestra y detente en cada operación para revisar sus datos. El resultado debe existir en el destino previsto con los campos correctos. Comprueba también el número de registros creados. Un indicador verde confirma una ejecución, pero podría haber escrito valores vacíos o en columnas equivocadas.'],
 ['Modificar un paso sin alterar el resto','Conserva una versión del flujo y modifica una sola transformación, por ejemplo normalizar el estado. Reutiliza la misma muestra para comparar salidas. Comprueba que el identificador y los demás campos permanecen intactos, y que el destino de ensayo sigue seleccionado.'],
 ['Localizar el primer paso que falla','Busca la primera operación cuya entrada es correcta y cuya salida no lo es. Un fallo final puede empezar varios pasos antes, cuando se perdió un campo. Distingue datos inválidos, permisos insuficientes y problemas temporales. Reintentar sirve para algunos fallos transitorios, pero no corrige una regla equivocada.'],
 ['Evitar duplicados y manejar entradas incompletas','Define qué significa repetir la misma solicitud. Si el identificador ya existe, la regla puede omitirla o actualizarla; no debe crear otra por accidente. Prueba además una entrada incompleta. Registra el resultado esperado de cada rama y comprueba el destino después de repetir el evento.'],
 ['Documentar activación, pausa y recuperación','Conserva la configuración del flujo sin incluir secretos en el documento. Explica qué lo activa, dónde consultar ejecuciones y cómo detenerlo. Comprueba qué información incluye una exportación y qué conexiones hay que configurar de nuevo. Documenta cómo reanudar sin volver a crear resultados ya guardados.'],
 ['Pasar de la prueba a un proceso mantenible','Empieza con pocas ejecuciones observadas. Mide duración, resultados correctos, repeticiones y fallos. Asigna quién revisa las excepciones y con qué frecuencia. Un flujo es mantenible cuando otra persona puede entender una ejecución y decidir si corregir datos, reintentar o detenerlo.'],
 ],en:[
 ['Describe the manual process','Identify what arrives, the decision and the destination. Missing decision information needs another step or human review.'],['Prepare test connections','Use fictional records and an identifiable test destination. Check connection identity and permissions before enabling continuous execution.'],['Follow a record through the flow','Trace the sample identifier through every operation’s input and output so failures and replays remain attributable.'],['Define field validation','Specify required fields, types and ranges, preserve identifiers and route invalid input explicitly.'],['Inspect the first execution','Check actual destination values and record count. A successful operation can still write empty or incorrectly mapped data.'],['Change one transformation','Keep a flow version and compare the same sample after changing one mapping. Preserve other fields and the test destination.'],['Find the first failing step','Inspect the earliest mismatch, distinguishing invalid data, permissions and temporary failures. Retries cannot repair invalid rules.'],['Handle replays and incomplete input','Define whether an existing identifier is skipped or updated. Replaying must not accidentally duplicate a final record.'],['Document pause and recovery','Record triggers, run inspection and stopping instructions without secrets. Verify what exports omit and how replay avoids duplicates.'],['Maintain an observed process','Start with a small observed workload. Track successes, failures and repeats, and assign responsibility for exception review.'],
 ]},
 {ids:['sheets','airtable','postgres','supabase','notion','obsidian'],es:[
 ['Organizar información para poder consultarla','Define qué representa una unidad de información: una reserva, una tarea o una nota. Elige campos que describan esa unidad sin mezclar totales ni encabezados con registros. En una biblioteca de notas, usa títulos y relaciones claros. La estructura debe permitir responder la pregunta del ejercicio.'],
 ['Preparar una copia y una muestra conocida','Crea un espacio de ensayo y añade unos pocos registros cuya respuesta puedas calcular o localizar a mano. Separa la fuente original de la vista de consulta. Antes de importar más datos, comprueba que los números, fechas y nombres se conservan en los campos previstos.'],
 ['Distinguir registro, campo, relación y vista','Un registro representa una unidad; un campo describe una propiedad; una relación conecta unidades. Una vista selecciona cómo se muestran. Filtrar elementos no equivale a borrarlos. En notas enlazadas, el enlace conecta contenidos, pero no crea por sí solo una regla de integridad o un permiso de acceso.'],
 ['Formular una consulta y su respuesta esperada','Escribe la pregunta antes de configurar el filtro o cálculo: «¿cuáles siguen pendientes?» o «¿cuánto suman estos importes?». Identifica los campos necesarios y calcula la respuesta sobre la muestra. Esto permite distinguir un resultado correcto de una vista que parece ordenada pero omite registros.'],
 ['Crear la consulta y contrastar los registros','Aplica la operación sobre la muestra y revisa tanto el resultado como los registros que lo producen. Un total puede parecer razonable aunque falte una fila. En una consulta filtrada, cuenta coincidencias y verifica un caso excluido. Conserva la pregunta junto a la consulta para recordar su propósito.'],
 ['Mejorar la estructura sin perder datos','Antes de cambiar un campo o una relación, conserva una copia y revisa las vistas que dependen de él. Modifica una decisión y vuelve a ejecutar la consulta conocida. Una etiqueta más clara ayuda al lector; un cambio de tipo puede alterar ordenaciones y cálculos y requiere otra comprobación.'],
 ['Detectar datos que parecen iguales y no lo son','Un número guardado como texto, un espacio al final o un estado escrito de dos maneras pueden cambiar el resultado. Inspecciona un registro que no aparece donde esperabas. Corrige la causa en una copia y repite la consulta, conservando la referencia original para verificar el efecto.'],
 ['Comprobar ausencias, duplicados y acceso','Prueba un campo vacío y dos registros con el mismo identificador. Decide qué debe permitirse según el diseño. Si existen datos privados, comprueba además el acceso con cada identidad de prueba: ocultar una vista no demuestra que otro usuario no pueda consultar el dato directamente.'],
 ['Compartir una vista y conservar una copia','Decide si el destinatario necesita leer, editar o importar. Una exportación puede no conservar relaciones, fórmulas o permisos; revisa el archivo resultante. Mantén una copia de los datos y documenta cómo reconstruir la consulta o vista que responde a la pregunta del ejercicio.'],
 ['Convertir la estructura en una herramienta de trabajo','Prueba consultas reales sobre una muestra permitida. Documenta quién mantiene los campos y cómo se corrigen registros incorrectos. Mide cuánto tarda una persona en encontrar una respuesta y si llega a la conclusión correcta, no solo cuánto tarda en abrir la base o la nota.'],
 ],en:[
 ['Structure information for a question','Define one record or note and its properties. Keep totals and headings separate from data. Structure should support the exercise question.'],['Prepare a known sample','Use a practice copy with a few manually checkable records. Verify types and field placement before adding volume.'],['Distinguish records, fields and views','A view changes presentation; filtering does not delete records. Note links are not automatically integrity rules or access controls.'],['Write the query and expected answer','State the question before creating a filter or calculation, then solve the sample manually.'],['Check both results and source records','Verify included and excluded records as well as totals. Keep the question beside its query.'],['Change structure carefully','Keep a copy and inspect dependent views before modifying fields. Re-run the known query after each structural decision.'],['Find subtly different data','Text numbers, trailing spaces and inconsistent status labels can change results. Inspect a wrongly excluded record.'],['Test missing values, duplicates and access','Define duplicate behavior and check private-data access with separate test identities; hidden views alone do not establish isolation.'],['Share and preserve a copy','Choose read, edit or import access. Verify whether export preserves formulas, relationships and permissions.'],['Use the structure in daily work','Document maintenance and corrections. Measure whether someone finds the right answer, not merely whether the workspace opens.'],
 ]},
 {ids:['base44','bolt','replit','lovable','v0','framer','tailwind'],es:[
 ['Diseñar una página para una acción concreta','Define qué necesita hacer el visitante: entender la oferta y dejar un correo de interés. Una lista de funciones no sustituye ese recorrido. Escribe el contenido esencial y la acción principal antes de pedir colores o efectos. El ejemplo utiliza una academia ficticia para concentrarse en el aprendizaje.'],
 ['Preparar el proyecto y el contenido','Crea una copia de práctica y reúne título, descripción del curso y texto del botón. Decide qué ocurrirá al enviar el formulario. Mostrar una confirmación en pantalla no significa que los datos se guarden: especifica si esta versión es una demostración local o tiene un destino configurado.'],
 ['Distinguir estructura, estilo y comportamiento','La estructura organiza títulos, párrafos y controles. El estilo determina cómo se ven. El comportamiento responde a acciones como enviar un formulario. Revisar estas capas por separado ayuda a explicar por qué un botón puede verse bien y no hacer nada, o funcionar y resultar ilegible.'],
 ['Escribir requisitos para móvil y formulario','Pide título, descripción, campo de correo y botón con etiqueta clara. Define qué pasa con un correo vacío o inválido y con uno válido. Incluye una comprobación con teclado y una pantalla estrecha. «Responsive» no sustituye indicar qué contenido y acciones deben seguir disponibles.'],
 ['Construir el recorrido de interés','Abre la vista previa y recorre la página como visitante. Lee la oferta, localiza el campo, introduce un correo y observa la confirmación. Repite con un dato inválido. Si existe almacenamiento, verifica el registro en el destino; si solo es una demo, conserva esa limitación en las instrucciones.'],
 ['Mejorar legibilidad sin romper la interacción','Modifica una decisión visual, por ejemplo el ancho de lectura o el contraste del botón. Compara la misma pantalla antes y después. Comprueba que la etiqueta, el foco del teclado y el mensaje de error siguen visibles. Una captura atractiva no permite verificar el comportamiento del formulario.'],
 ['Separar fallos visuales y de funcionamiento','Si el botón no responde, comprueba si se puede activar y qué evento produce. Si el texto se corta, revisa el ancho y el ajuste de línea. Reproduce el defecto con el tamaño y los datos originales. Cambiar todo el diseño impediría saber qué corrigió realmente el fallo.'],
 ['Probar textos largos y navegación','Ensaya un título largo, un correo inválido y una pantalla de 320 píxeles. Navega con teclado y vuelve atrás después de la confirmación. Comprueba que no desaparezcan controles ni aparezca desplazamiento horizontal innecesario. Verifica rutas internas también después de recargar.'],
 ['Entregar una vista accesible al destinatario','Distingue el enlace del editor del enlace de vista previa o publicación. Abre el enlace que recibirá la persona en una sesión separada. Documenta qué datos guarda la página y qué requiere configuración adicional. Conserva la versión anterior para poder recuperar el recorrido comprobado.'],
 ['Evaluar si la página cumple su objetivo','Pide a una persona que explique la oferta y complete el formulario de prueba sin instrucciones verbales. Observa dónde duda y qué mensajes no entiende. Prioriza una mejora basada en esa observación y repite el recorrido; no confundas tu preferencia estética con una dificultad demostrada.'],
 ],en:[
 ['Design around one visitor action','Define the offer and interest-form journey before visual effects. Use a fictional academy to keep scope clear.'],['Prepare project and content','Gather title, course description and button text. Specify whether confirmation is only a local demo or data is actually stored.'],['Separate structure, style and behavior','A control can look correct yet do nothing. Inspect content hierarchy, appearance and interaction separately.'],['Specify mobile and form behavior','Define empty, invalid and valid email cases, keyboard use and narrow-screen requirements.'],['Build the complete interest journey','Read the offer, submit an email and inspect confirmation. Verify actual storage separately where configured.'],['Improve readability without regressions','Compare one visual change and recheck labels, keyboard focus and error visibility.'],['Distinguish visual and functional bugs','Reproduce using original size and input. Check activation separately from layout rather than redesigning everything.'],['Test long content and navigation','Use long titles, invalid email, keyboard navigation and a 320-pixel screen. Reload internal routes.'],['Deliver the correct recipient link','Distinguish editor and public/preview links. Open in a separate session and document storage limitations.'],['Observe whether the page meets its purpose','Ask someone to explain the offer and complete the test form without verbal help. Prioritize observed friction.'],
 ]},
 {ids:['canva','figma','midjourney','nano-banana','higgsfield','seedance-2-5','heygen','descript','runway','elevenlabs','gamma'],es:[
 ['Definir una pieza para un destinatario','Un encargo creativo necesita propósito, contenido y formato. Explica qué debe entender quien vea o escuche la pieza y dónde la utilizará. Distingue el mensaje de las decisiones de estilo. En una imagen necesitas jerarquía y espacio; en una secuencia o narración necesitas además orden y continuidad.'],
 ['Preparar fuentes y material de trabajo','Reúne el texto, referencias y archivos del ejercicio. Identifica cuáles son originales y cuáles son resultados de edición o generación. Conserva la fuente sin cambios. Si trabajas con voz o imagen de una persona, utiliza material autorizado; en esta práctica puedes emplear textos propios y escenas ficticias.'],
 ['Comprender composición y secuencia','La composición organiza lo que se percibe primero y lo que sirve de apoyo. La secuencia organiza el orden de lectura, escenas o frases. Identifica el elemento principal, el contexto y el cierre del ejemplo. No añadas elementos decorativos que compitan con la información necesaria para entender el mensaje.'],
 ['Preparar un encargo que se pueda revisar','Especifica contenido obligatorio, formato y criterios de revisión. Para una imagen, indica dónde debe quedar espacio para texto; para audio, el texto exacto; para vídeo, el orden de escenas; para diapositivas, la función de cada página. Evita pedir mejoras sin describir qué debe cambiar en el resultado.'],
 ['Producir una primera versión completa','Crea una versión que contenga todo el mensaje antes de afinar detalles. Revisa la pieza completa: no te quedes solo con la primera imagen, frase o diapositiva. Comprueba que el cierre no se corta y que el material exportado conserva los elementos esenciales del encargo.'],
 ['Revisar una decisión creativa','Elige un defecto observable: falta de espacio, voz demasiado rápida, transición confusa o título cortado. Mantén el contenido y modifica la decisión que lo causa. En una generación, guarda los parámetros y la versión elegida para poder comparar, aunque una nueva ejecución no produzca píxeles idénticos.'],
 ['Diagnosticar diferencias entre editor y archivo','Abre el resultado fuera del editor. Si falta audio, texto o una escena, compara la selección de exportación con la línea de tiempo o las páginas. Si la composición no cumple, vuelve al encargo y señala la condición incumplida. No confundas una miniatura correcta con un archivo final verificado.'],
 ['Comprobar legibilidad y reproducción','Revisa el tamaño de uso previsto y reproduce el archivo completo cuando tenga duración. Comprueba texto pequeño, márgenes, principio y final. Si hay voz, contrasta nombres y números con el guion. Anota las diferencias observables, porque la impresión general puede ocultar una omisión importante.'],
 ['Preparar un archivo de entrega','Conserva el proyecto editable y exporta el formato que necesita el destinatario. Identifica versión y finalidad en el nombre. Comprueba que el archivo abre en otra aplicación y que no depende de una vista privada del editor. Incluye el guion o texto de referencia cuando sea necesario para futuras revisiones.'],
 ['Justificar decisiones de comunicación','Presenta la pieza junto al encargo original. Explica cómo composición, ritmo o estructura ayudan a comprender el mensaje. Pide a una persona que describa qué entendió sin mostrarle tus instrucciones. Utiliza esa respuesta para decidir una mejora concreta y comprobarla en una segunda versión.'],
 ],en:[
 ['Define a piece for its audience','Specify purpose, content and format. Separate message from style; timed media also needs sequence and continuity.'],['Prepare sources and materials','Keep original text and files separate from generated or edited results. Use authorized material and fictional practice scenes.'],['Understand composition and sequence','Identify the main element, supporting context and ending. Decoration should not compete with the message.'],['Write a reviewable creative brief','Specify required content and format: text space for images, exact narration text, scene order or slide roles.'],['Produce a complete first version','Review the entire piece, including its ending and exported content, before polishing details.'],['Revise one creative decision','Name an observable defect and preserve content while correcting composition, pacing or hierarchy. Keep versions and generation settings.'],['Diagnose editor/export differences','Open outside the editor and compare export selection with scenes or pages. A correct thumbnail is not a verified file.'],['Check readability and playback','Inspect intended display size and complete playback. Compare names and numbers in narration with the script.'],['Prepare recipient files','Keep editable source and an appropriate export with identifiable version. Verify it in another application.'],['Explain communication decisions','Compare with the original brief and ask a viewer what they understood without showing your instructions.'],
 ]},
 {ids:['notebooklm','perplexity','huggingface','replicate'],es:[
 ['Formular una pregunta y una evidencia necesaria','Distingue obtener una respuesta de establecer en qué se apoya. En investigación necesitas una fuente pertinente; al comparar modelos necesitas una muestra común y criterios. Define qué afirmación o resultado quieres comprobar antes de buscar o ejecutar, para evitar elegir solo ejemplos favorables.'],
 ['Preparar fuentes o muestras comparables','Reúne documentos o entradas que puedas revisar y anota su origen. Si comparas alternativas, utiliza la misma muestra en todas. Identifica versión y fecha cuando influyan en el resultado. Una referencia incompleta dificulta repetir la comparación o saber si una diferencia se debe al material de entrada.'],
 ['Relacionar entrada, referencia y salida','Sigue el fragmento o muestra desde su origen hasta la respuesta. Una cita debe respaldar la afirmación cercana, no simplemente tratar el mismo tema. En una ejecución de modelo, conserva la entrada y los parámetros para interpretar la salida. La etiqueta de un sistema no demuestra por sí sola su calidad.'],
 ['Definir un criterio de comparación','Escribe qué considerarás correcto, incompleto o no respaldado. Para horarios, cada sede y hora necesitan una referencia; para clasificación, cada texto necesita una etiqueta de referencia definida con antelación. Evita decidir la respuesta correcta después de ver qué alternativa produce el resultado que prefieres.'],
 ['Obtener y contrastar el resultado','Abre la fuente citada o revisa la salida completa de la ejecución. Localiza el fragmento exacto que respalda la conclusión. Cuando la evidencia no permita resolver una parte, márcala como pendiente. Un enlace válido puede apuntar a una página que no sostiene la afirmación.'],
 ['Afinar la pregunta o configuración','Cambia una condición y conserva el resto de la muestra para comparar. Una pregunta más precisa puede recuperar información más pertinente, pero no crea evidencia inexistente. En una comparación de modelos, registra el parámetro cambiado y evita atribuirle una mejora que no has observado en varias muestras.'],
 ['Investigar una respuesta no respaldada','Identifica si el problema está en la fuente, en la selección del fragmento o en la conclusión. Si la fuente no incluye el dato, insistir en la misma pregunta no lo vuelve disponible. Si el dato existe, reformula para acotar sede, fecha o categoría y vuelve a contrastar con el original.'],
 ['Probar ausencia, contradicción y variación','Incluye una pregunta sin respuesta en las fuentes o una muestra difícil de clasificar. La salida debe reconocer incertidumbre o mostrar el conflicto. Registra qué variación cambió el resultado. Tres ejemplos no bastan para estimar un rendimiento general; sirven para aprender el procedimiento de comparación.'],
 ['Conservar una comparación reproducible','Guarda la pregunta, muestras, referencias y configuración junto al resultado. En un informe, separa hechos, inferencias y dudas. Para ejecuciones, conserva la versión seleccionada y los parámetros disponibles. Otra persona debe poder entender de dónde procede cada conclusión y qué faltaría para repetirla.'],
 ['Presentar conclusiones con sus límites','Explica qué permiten concluir las muestras y qué no. Una recomendación debe relacionarse con los criterios definidos, no solo con la respuesta que parece más convincente. Indica qué comprobación adicional reduciría la principal incertidumbre antes de ampliar el uso a un proyecto real.'],
 ],en:[
 ['Define the question and required evidence','Distinguish obtaining an answer from establishing support. Use relevant sources or a common model-comparison sample and criteria.'],['Prepare comparable sources or samples','Record origins, versions and dates where relevant. Keep input consistent across alternatives.'],['Connect input, reference and result','A citation must support the specific claim. A model label alone does not establish output quality.'],['Define comparison criteria first','Decide correct, incomplete and unsupported outcomes before inspecting results.'],['Inspect the result and its support','Open the actual source or output. Valid links may still fail to support the associated claim.'],['Refine one question or setting','Keep the sample constant and record changes. More precise wording cannot create missing evidence.'],['Investigate unsupported conclusions','Locate whether the failure is in source availability, retrieval or interpretation, then recheck the original.'],['Test absence and uncertainty','Include unanswerable questions or difficult samples. Three examples teach comparison but cannot establish general performance.'],['Keep a reproducible record','Save questions, inputs, references, version and settings. Separate facts, inference and unresolved questions.'],['Present conclusions with limits','Connect conclusions to predefined criteria and identify the next check needed before broader use.'],
 ]},
 {ids:['docker','vercel'],es:[
 ['Definir qué significa ejecutar o publicar','Una aplicación necesita un entorno de ejecución. El código puede existir sin que el servicio esté disponible. Define cómo comprobarás que arranca, qué dirección o puerto utiliza y qué recorrido debe funcionar. Una publicación añade además la perspectiva de una persona que entra desde otra sesión.'],
 ['Preparar requisitos y configuración','Revisa los archivos del proyecto y las instrucciones de arranque. Identifica qué configuración corresponde al entorno de ensayo y qué variables necesita. No copies valores secretos a las instrucciones. Anota nombres y finalidad de las variables para que otra persona pueda configurar su propio entorno.'],
 ['Seguir construcción, ejecución y petición','Construir prepara los archivos o la imagen que se ejecutará. Ejecutar inicia el proceso. Una petición comprueba que responde. Separa estos estados: una construcción correcta todavía puede fallar al iniciar, y un proceso activo puede no responder en el puerto esperado.'],
 ['Definir una comprobación de disponibilidad','Elige una dirección y una acción concreta que deban funcionar. Documenta la respuesta esperada y una ruta interna que puedas recargar. No uses solo «está desplegado» como criterio: comprueba que el recorrido de la muestra sigue disponible en el entorno resultante.'],
 ['Arrancar y comprobar la aplicación','Ejecuta el procedimiento del proyecto e inspecciona los registros del proceso. Abre la dirección resultante y realiza la acción de prueba. Si la aplicación usa un formulario, comprueba su resultado además de la carga inicial. Conserva la versión que estás comprobando.'],
 ['Cambiar configuración de forma controlada','Conserva una versión conocida y modifica una sola configuración de ensayo. Relaciona su efecto con el resultado esperado. Si cambias a la vez código, variables y entorno, será más difícil localizar la causa de un fallo. Repite la comprobación funcional tras el cambio.'],
 ['Distinguir fallo de construcción y de ejecución','Localiza la fase donde aparece el primer error. Un archivo ausente al construir no se resuelve reiniciando el proceso; un puerto incorrecto no implica necesariamente un defecto de la página. Conserva el mensaje y contrasta la configuración con las instrucciones del proyecto.'],
 ['Probar recarga, reinicio y rutas','Abre una ruta interna directamente, recarga y vuelve a iniciar el entorno de ensayo. Comprueba qué datos persisten y cuáles son temporales. Si dependes de otro servicio, documenta qué ve el usuario cuando no está disponible. No supongas que el disco local conserva datos en cualquier alojamiento.'],
 ['Conservar una versión recuperable','Identifica el artefacto o despliegue que superó las pruebas. Documenta cómo seleccionar o recrear esa versión usando el mecanismo del entorno. Verifica la recuperación en un ensayo y repite la misma comprobación de disponibilidad y funcionamiento.'],
 ['Entregar acceso e instrucciones de mantenimiento','Entrega la dirección correcta, la versión comprobada y las instrucciones de arranque o despliegue. Incluye dónde mirar los registros y cómo detener o recuperar el servicio. Verifica el acceso desde una sesión separada para no depender de permisos de tu cuenta.'],
 ],en:[
 ['Define running and publishing','Code existence does not establish service availability. Specify address, port and the user journey to verify.'],['Prepare requirements and configuration','Read startup instructions, identify test configuration and document variable names without secret values.'],['Separate build, process and request','A successful build can fail at startup; an active process may still respond on the wrong port.'],['Define an availability check','Specify an address, expected response and reloadable internal route, not just a deployment status.'],['Start and inspect the application','Inspect process logs, open the resulting address and complete the functional sample. Record the version.'],['Change configuration deliberately','Change one relevant setting while retaining known code and repeat the functional check.'],['Distinguish build and runtime failures','Locate the earliest error and compare configuration with project instructions before restarting or editing.'],['Test reloads, restarts and routes','Inspect persistence and direct internal navigation. Do not assume local storage survives every hosting environment.'],['Preserve a recoverable version','Identify the checked artifact and verify recovery using the environment’s supported mechanism.'],['Hand over access and maintenance','Provide address, checked version, startup instructions, logs and recovery steps. Verify a separate recipient session.'],
 ]},
 {ids:['gmail','slack','telegram','whatsapp','wispr-flow'],es:[
 ['Preparar una comunicación fiel al original','El objetivo es transmitir información sin cambiar nombres, fechas ni compromisos. Distingue redactar o transcribir de enviar. Un borrador permite revisar el contenido antes de que otra persona lo reciba. En dictado, el trabajo consiste en convertir voz en texto y corregirlo; no implica que exista una automatización.'],
 ['Preparar el destino de escritura','Abre un borrador o campo de prueba y confirma dónde aparecerá el texto. En dictado, comprueba el permiso de micrófono y el campo que tiene el foco. En mensajería, verifica la conversación o destinatario antes de preparar contenido. Mantén la práctica sin envío salvo que el destino de ensayo esté autorizado.'],
 ['Distinguir fuente, borrador y envío','La fuente contiene lo que sabes; el borrador organiza cómo comunicarlo; el envío lo entrega. Revisa cada transición. En una transcripción, reconocer palabras no garantiza conservar puntuación, nombres propios o cifras. En una respuesta, una frase amable no debe convertirse en una promesa que la fuente no permite hacer.'],
 ['Definir qué información debe conservarse','Subraya identificadores, nombres, cantidades y fechas del ejemplo. Escribe qué datos no están confirmados. Para un dictado, prepara una frase que contenga un nombre y una hora. Para una respuesta, define qué puedes afirmar y qué debes dejar pendiente de confirmación.'],
 ['Crear y revisar el borrador completo','Produce el texto y léelo comparándolo con la fuente. Revisa por separado nombres y números, porque un texto natural puede contener una cifra incorrecta. Confirma que el resultado permanece en el campo o borrador previsto. La revisión precede a cualquier envío externo.'],
 ['Mejorar claridad sin añadir compromisos','Acorta o reorganiza el borrador manteniendo los hechos. Una solicitud de cambio no equivale a una reserva ya modificada: si no has comprobado disponibilidad, el mensaje debe indicar que la solicitud se revisará. En dictado, corrige primero el contenido y después la puntuación.'],
 ['Localizar una transcripción o respuesta incorrecta','Compara el fragmento erróneo con su fuente. Si se reconoce mal un nombre, corrígelo y prueba otra frase que lo incluya. Si una respuesta inventa una confirmación, cambia la instrucción para separar recepción de solicitud y confirmación de ejecución. Conserva el ejemplo que provocó el fallo.'],
 ['Comprobar ambigüedades y datos sensibles al error','Prueba nombres parecidos, números y una fecha incompleta. El borrador debe preservar la incertidumbre en lugar de elegir un dato arbitrario. Verifica además que el texto no aparece en otro campo por un cambio de foco o en una conversación distinta por una selección anterior.'],
 ['Conservar una plantilla sin datos antiguos','Guarda una estructura reutilizable y marca claramente los campos que deben sustituirse. Revisa destinatario, identificador y fecha en cada uso. Una plantilla que conserva una reserva anterior puede producir un mensaje gramaticalmente correcto y operativamente equivocado.'],
 ['Aplicar la revisión a comunicaciones nuevas','Prepara tres borradores o dictados y mide el tiempo incluyendo correcciones. Cuenta errores en nombres, cantidades y compromisos, no solo palabras por minuto. La práctica termina con textos revisados; cualquier envío requiere comprobar el destinatario y que el contenido esté listo para ser comunicado.'],
 ],en:[
 ['Preserve the original meaning','Separate drafting or transcription from sending. Dictation converts voice to text; it does not imply an automation.'],['Prepare the writing destination','Confirm the draft or focused field. For dictation check microphone access; for messaging check the intended test conversation.'],['Separate source, draft and send','Natural text can still change names, figures or commitments. Review each transition before delivery.'],['Define information to preserve','Mark names, identifiers, quantities and dates, including what is unconfirmed.'],['Create and review a complete draft','Compare with the source, checking numbers and names separately. Keep it in the intended draft or field.'],['Improve clarity without new commitments','Receiving a rescheduling request is not confirmation that the booking changed. Preserve that distinction when editing tone.'],['Diagnose incorrect wording','Compare the incorrect fragment with its source and retest another example containing the same challenge.'],['Check ambiguity and transcription risks','Try similar names, numbers and incomplete dates. Preserve uncertainty and verify the focused field or conversation.'],['Keep templates free of old data','Clearly mark replacement fields and recheck recipient, identifier and date every time.'],['Apply review to new communications','Measure three drafts including correction time and factual errors, not just writing speed. Verify recipients before any authorized delivery.'],
 ]},
]
export function domainFor(id:string,index:number,en:boolean) {
 const d=domains.find(d=>d.ids.includes(id))
 if(!d)throw new Error(`Missing institutional curriculum domain: ${id}`)
 const [title,text]=(en?d.en:d.es)[index]
 return {title,text}
}
