import type { ToolPage } from './types'
import { codexPath } from './codex-path'
import { expandCodex } from './codex-study'
import { method, type Study } from './study-method'
import { domainFor } from './study-domains'
import { workedSolution } from './tool-worked'

export type PathLesson = { id: string; title: string; purpose: string; explanation: string[]; example: string; steps: string[]; check: string; errors: string[]; study?: Study }
// Concrete practice briefs. These are teaching exercises, never claims of a completed external run.
const cases: Record<string, [string, string, string, string]> = {
  codex: ['Un formulario de reservas acepta cero huéspedes.', 'A booking form accepts zero guests.', '1 huésped se acepta; 0 muestra un error y no crea la reserva.', '1 guest is accepted; 0 shows an error and creates no booking.'],
  cursor: ['El buscador distingue mayúsculas: Ana encuentra un cliente, ana no.', 'Search is case sensitive: Ana finds a customer, ana does not.', 'Ambas búsquedas devuelven el mismo cliente y la lista vacía sigue funcionando.', 'Both searches return the same customer and empty results still work.'],
  'claude-code': ['Una función suma precios como texto y devuelve 1020 para 10 y 20.', 'A function joins prices as text and returns 1020 for 10 and 20.', 'Devuelve 30; una entrada no numérica produce un error controlado.', 'It returns 30; nonnumeric input produces a controlled error.'],
  github: ['Un repositorio de práctica necesita instrucciones de instalación.', 'A practice repository needs installation instructions.', 'Un README se revisa mediante un pull request y otra persona puede seguirlo.', 'A README is reviewed through a pull request and another person can follow it.'],
  n8n: ['Un registro ficticio tiene id RES-001, huéspedes 2 y estado nuevo.', 'A fictional record has id RES-001, guests 2 and status new.', 'El flujo de prueba valida el registro; repetir RES-001 no genera dos resultados finales.', 'The test workflow validates the record; replaying RES-001 does not create two final results.'],
  make: ['Un formulario de prueba recibe id SOL-001 y servicio limpieza.', 'A test form receives id REQ-001 and service cleaning.', 'Un escenario guarda una solicitud de prueba y conserva su identificador.', 'A scenario saves one test request and preserves its identifier.'],
  zapier: ['Una fila de prueba contiene nombre Ana y estado pendiente.', 'A test row contains name Ana and status pending.', 'El Zap crea un único registro en un destino de prueba, con ambos campos correctos.', 'The Zap creates one record in a test destination with both fields correct.'],
  pipedream: ['Un evento de prueba contiene precio 10 y cantidad 3.', 'A test event contains price 10 and quantity 3.', 'La ejecución devuelve total 30 y rechaza cantidades negativas.', 'The run returns total 30 and rejects negative quantities.'],
  python: ['CSV: producto,cantidad,precio; taza,2,5; libro,1,12.', 'CSV: product,quantity,price; mug,2,5; book,1,12.', 'El script calcula 22 y señala las filas con cantidades inválidas.', 'The script calculates 22 and flags rows with invalid quantities.'],
  node: ['Un programa recibe dos argumentos: 10 y 20.', 'A program receives two arguments: 10 and 20.', 'La terminal muestra 30; sin argumentos explica cómo usarlo.', 'The terminal displays 30; without arguments it explains usage.'],
  typescript: ['Una reserva tiene id de texto y huéspedes de tipo número.', 'A booking has a text id and numeric guests.', 'El compilador detecta asignar texto a huéspedes; la app también valida los datos recibidos.', 'The compiler catches assigning text to guests; the app also validates incoming data.'],
  react: ['Una lista de tres tareas necesita marcar cada tarea terminada.', 'A list of three tasks needs individual completion controls.', 'Marcar una tarea cambia solo esa tarea; funciona con teclado.', 'Checking one task changes only that task; keyboard operation works.'],
  tailwind: ['Una tarjeta muestra un título largo, precio y botón de reserva.', 'A card shows a long title, price and booking button.', 'A 320 y 1440 píxeles el texto no se corta y el botón sigue accesible.', 'At 320 and 1440 pixels text is not clipped and the button remains accessible.'],
  vscode: ['Una carpeta contiene index.html y styles.css.', 'A folder contains index.html and styles.css.', 'Encuentras un selector, cambias un color y revisas solo ese cambio.', 'You find a selector, change one color and review only that change.'],
  docker: ['Una aplicación de prueba debe arrancar en un entorno reproducible.', 'A test application needs a reproducible runtime.', 'El contenedor arranca, responde en el puerto documentado y se puede detener.', 'The container starts, responds on the documented port and can be stopped.'],
  postgres: ['Tabla de prueba reservas: R1 por 20 y R2 por 30.', 'Test bookings table: R1 for 20 and R2 for 30.', 'Una consulta devuelve total 50; insertar R1 de nuevo respeta la regla de unicidad.', 'A query returns total 50; inserting R1 again respects uniqueness.'],
  supabase: ['Dos usuarios de prueba tienen una nota privada cada uno.', 'Two test users each have one private note.', 'Cada usuario lee su nota y recibe denegación al pedir la del otro.', 'Each user reads their own note and is denied access to the other.'],
  vercel: ['Una web de prueba muestra un formulario y una página de confirmación.', 'A test website displays a form and confirmation page.', 'La vista previa carga, enviar datos válidos funciona y la recarga conserva la ruta.', 'The preview loads, valid submission works and reloading preserves the route.'],
  sheets: ['Filas: limpieza 40, limpieza 60, reparación 25.', 'Rows: cleaning 40, cleaning 60, repair 25.', 'El total es 125 y el subtotal de limpieza es 100.', 'The total is 125 and the cleaning subtotal is 100.'],
  airtable: ['Tres solicitudes: dos pendientes y una resuelta.', 'Three requests: two pending and one resolved.', 'Una vista filtrada muestra exactamente las dos pendientes.', 'A filtered view shows exactly the two pending requests.'],
  notion: ['Un proyecto necesita tres tareas con responsable y fecha.', 'A project needs three tasks with owner and date.', 'Puedes filtrar tareas pendientes y abrir cada ficha con su información.', 'You can filter pending tasks and open each record with its details.'],
  obsidian: ['Dos notas: Proyecto reservas y Decisiones técnicas.', 'Two notes: Booking project and Technical decisions.', 'El enlace entre ambas abre la nota correcta y una búsqueda encuentra la decisión.', 'The link opens the correct note and search finds the decision.'],
  gmail: ['Un correo ficticio pide cambiar la reserva R1 del lunes al martes.', 'A fictional email asks to move booking R1 from Monday to Tuesday.', 'Un borrador recoge R1 y la fecha solicitada sin afirmar que el cambio ya esté confirmado; permanece sin enviar.', 'A draft records R1 and the requested date without claiming the change is confirmed; it remains unsent.'],
  slack: ['Un equipo de prueba necesita un resumen de tres incidencias.', 'A test team needs a summary of three incidents.', 'Un borrador distingue incidencia, responsable y siguiente paso, sin publicar.', 'A draft separates incident, owner and next step without posting.'],
  telegram: ['Una notificación de prueba informa que RES-001 falló.', 'A test notification reports that RES-001 failed.', 'El contenido identifica el registro y el error; solo se prueba en un chat autorizado.', 'The content identifies record and error; testing uses only an authorized chat.'],
  whatsapp: ['Una persona pide el horario de una tienda ficticia: 9 a 17.', 'Someone asks for a fictional shop schedule: 9 to 17.', 'El borrador responde 9 a 17 y no inventa aperturas en festivos.', 'The draft answers 9 to 17 and does not invent holiday opening hours.'],
  'wispr-flow': ['Dicta: Reserva de Ana Pérez, dos huéspedes, martes a las 17:30.', 'Dictate: Booking for Ana Perez, two guests, Tuesday at 17:30.', 'El texto conserva nombre, cantidad, día y hora después de revisarlo.', 'The text preserves name, quantity, day and time after review.'],
  notebooklm: ['Dos documentos ficticios dicen apertura a las 9 y cierre a las 17.', 'Two fictional documents state opening at 9 and closing at 17.', 'La respuesta cita el documento que respalda cada horario y no inventa festivos.', 'The answer cites the document supporting each time and does not invent holidays.'],
  perplexity: ['Investiga cómo documentar una política de devoluciones para un caso ficticio.', 'Research how to document a returns policy for a fictional case.', 'Cada afirmación factual tiene una fuente abierta y una fecha; separas dudas de hechos.', 'Each factual claim has an opened source and date; you separate uncertainty from facts.'],
  ollama: ['Una nota ficticia contiene tres tareas y dos fechas.', 'A fictional note contains three tasks and two dates.', 'La respuesta conserva las tres tareas y fechas; compruebas dónde se ejecuta el modelo.', 'The answer preserves three tasks and dates; you verify where the model runs.'],
  langchain: ['Tres fragmentos de prueba describen horarios diferentes por sede.', 'Three test snippets describe different schedules per branch.', 'La respuesta usa el fragmento de la sede correcta y devuelve su referencia.', 'The answer uses the correct branch snippet and returns its reference.'],
  huggingface: ['Compara dos modelos para clasificar tres textos ficticios.', 'Compare two models for classifying three fictional texts.', 'Registras licencia, requisitos y las etiquetas obtenidas con la misma muestra.', 'You record license, requirements and labels from the same sample.'],
  replicate: ['Una muestra pública debe pasar por un modelo seleccionado.', 'A public sample must be processed by a selected model.', 'Conservas versión, parámetros y salida; compruebas el consumo antes de repetir.', 'You preserve version, parameters and output; check usage before repeating.'],
  colab: ['Un notebook calcula la media de 10, 20 y 30.', 'A notebook calculates the mean of 10, 20 and 30.', 'Tras reiniciar y ejecutar en orden devuelve 20 sin depender de variables antiguas.', 'After restarting and running in order it returns 20 without stale variables.'],
}
const textTools = ['openai','anthropic','claude','gemini','copilot']
const siteTools = ['base44','bolt','replit','lovable','v0','framer']
const imageTools = ['canva','figma','midjourney','nano-banana']
const videoTools = ['higgsfield','seedance-2-5','heygen','descript','runway']
for (const id of textTools) cases[id] = ['Nota: Ana prepara presupuesto el martes; Luis revisa el jueves. No hay importe acordado.', 'Note: Ana prepares a quote Tuesday; Luis reviews Thursday. No amount is agreed.', 'Una tabla recoge las dos tareas y fechas; el importe figura como no indicado.', 'A table lists both tasks and dates; amount is marked unspecified.']
for (const id of siteTools) cases[id] = ['Una página de una academia ficticia ofrece un curso y un formulario de interés.', 'A fictional academy page offers a course and interest form.', 'El formulario valida correo y muestra confirmación; el menú funciona en móvil.', 'The form validates email and shows confirmation; mobile navigation works.']
for (const id of imageTools) cases[id] = ['Una academia ficticia necesita una pieza visual cuadrada con espacio para título.', 'A fictional academy needs a square visual with space for a title.', 'La exportación es cuadrada, se abre fuera del editor y mantiene el espacio de texto legible.', 'The export is square, opens outside the editor and keeps readable text space.']
for (const id of videoTools) cases[id] = ['Un vídeo de prueba enseña un escritorio antes y después de ordenarlo.', 'A test video shows a desk before and after organizing it.', 'El archivo reproduce ambas escenas en orden y no corta el final ni el audio.', 'The file plays both scenes in order and does not cut off the ending or audio.']
cases.elevenlabs = ['Texto propio: Bienvenido al curso. Hoy crearás tu primer proyecto.', 'Original text: Welcome to the course. Today you will create your first project.', 'El audio dice ambas frases completas con una voz autorizada y se reproduce fuera del editor.', 'Audio contains both full sentences using an authorized voice and plays outside the editor.']
cases.gamma = ['Tres diapositivas: problema, propuesta y siguiente paso para una academia ficticia.', 'Three slides: problem, proposal and next step for a fictional academy.', 'Las tres partes aparecen en orden y la exportación no corta títulos ni párrafos.', 'All three parts appear in order and export does not clip headings or paragraphs.']

export function toolPath(tool: ToolPage, en: boolean): PathLesson[] {
  if (tool.id === 'codex') return codexPath(en).map((lesson,index)=>expandCodex(lesson,index,en))
  if (!tool.guide) return []
  const sample=cases[tool.id]
  if (!sample) throw new Error(`Missing practice case: ${tool.id}`)
  const input=sample[en?1:0],output=sample[en?3:2]
  const actions = en ? [
    ['Read the sample and identify its input and recipient.', 'Write the expected result in your own words and separate what is out of scope.', 'Use the worked solution to check that every relevant value is retained.'],
    ['Open a dedicated practice space in the tool using its official access reference below.', 'Keep the source sample separately and identify where the result will be stored.', 'Close and reopen the space, checking that the same source is available.'],
    ['Locate the control or field that receives the sample.', 'Trace one specific value through the operation described above.', 'Draw its source, transformation and destination using the tool’s terms.'],
    ['Copy the sample into your practice space without adding unprovided information.', 'Write normal and incomplete-input expectations before running.', 'Compare your brief with the worked solution and resolve ambiguous rules.'],
    ['Apply the operation described in the worked solution to the sample.', 'Open the actual output and inspect every relevant value or behavior.', 'Record a comparison between the expected result and what you observed.'],
    ['Preserve the first result and name one observable defect.', 'Change the decision responsible while retaining the same source sample.', 'Compare both versions and recheck the original conditions.'],
    ['In a disposable copy, reproduce a missing required value or incorrect condition.', 'Locate the first mismatch and record a hypothesis and its diagnostic check.', 'Correct the cause, then rerun both the failing and original valid case.'],
    ['Prepare a normal case, a missing-value case and a relevant boundary variation.', 'Write the expected behavior for each before executing.', 'Run each case and record observations, including unresolved differences.'],
    ['Keep an identifiable checked version together with its source and instructions.', 'Open or recover it in a separate practice space using those instructions.', 'Verify content and behavior and document export or access limitations.'],
    ['Choose a new authorized task and define its recipient and expected result.', 'Complete three small trials, recording preparation, execution and review time.', 'Save the result and evidence in My project with limitations and the next improvement.'],
  ] : [
    ['Lee la muestra e identifica su entrada y quién necesita el resultado.', 'Escribe la salida esperada con tus palabras y separa lo que queda fuera del ejercicio.', 'Contrasta con la resolución comentada que se conservan los datos relevantes.'],
    ['Abre un espacio de práctica en la herramienta usando su referencia oficial de acceso, al final de la unidad.', 'Conserva la muestra original por separado e identifica dónde se guardará la salida.', 'Cierra y vuelve a abrir el espacio para comprobar que puedes retomar la misma muestra.'],
    ['Localiza el campo o control que recibe los datos de la muestra.', 'Sigue un valor concreto durante la operación explicada en esta unidad.', 'Dibuja origen, transformación y destino usando los nombres que ves en la herramienta.'],
    ['Copia la muestra en el espacio de práctica sin añadir datos que no proporciona.', 'Escribe qué debe ocurrir con una entrada válida y con una incompleta antes de ejecutar.', 'Contrasta el encargo con la resolución comentada y aclara las reglas ambiguas.'],
    ['Aplica a la muestra la operación descrita en la resolución comentada.', 'Abre la salida real y revisa cada dato o comportamiento relevante.', 'Registra la comparación entre el resultado esperado y lo que has observado.'],
    ['Conserva el primer resultado e identifica un defecto observable.', 'Modifica la decisión que lo provoca manteniendo la misma muestra de entrada.', 'Compara ambas versiones y repite las comprobaciones originales.'],
    ['En una copia desechable, reproduce la falta de un dato necesario o una condición incorrecta.', 'Localiza la primera diferencia y registra una hipótesis y una comprobación para investigarla.', 'Corrige la causa y repite tanto el caso que fallaba como el caso válido original.'],
    ['Prepara un caso normal, otro sin un dato y una variación de límite relevante para la tarea.', 'Escribe la respuesta esperada de cada caso antes de ejecutarlo.', 'Realiza las pruebas y registra lo observado, incluidas las diferencias pendientes.'],
    ['Conserva una versión identificable que haya pasado las comprobaciones, con su fuente e instrucciones.', 'Ábrela o recupérala en otro espacio de ensayo siguiendo únicamente esas instrucciones.', 'Verifica contenido y funcionamiento y documenta límites de exportación o acceso.'],
    ['Elige una tarea propia permitida y define su destinatario y resultado esperado.', 'Realiza tres ensayos pequeños, midiendo preparación, ejecución y revisión.', 'Guarda en Mi proyecto el resultado, las pruebas, sus límites y una mejora siguiente.'],
  ]
  return Array.from({length:10},(_,index)=>{
    const m=method(index,en),d=domainFor(tool.id,index,en)
    return {id:String(index+1).padStart(2,'0'),title:d.title,purpose:m.evidence,explanation:[d.text,...m.paragraphs],example:input,steps:actions[index],check:output,
      errors:[en?'Compare the first incorrect output with its source. Keep the complete message and the exact sample before changing the procedure.':'Compara la primera salida incorrecta con su origen. Conserva el mensaje completo y la muestra exacta antes de cambiar el procedimiento.',en?'If a prerequisite or product control is unavailable, consult the official reference and record the missing requirement; do not mark the execution as completed.':'Si falta un requisito o no encuentras un control, consulta la referencia oficial y registra lo que falta; no marques la ejecución como realizada.'],
      study:{objective:d.title,concepts:[{title:`${tool.label}: ${d.title.toLocaleLowerCase()}`,paragraphs:[d.text]},{title:m.title,paragraphs:m.paragraphs}],solution:workedSolution(tool.id,en),reasoning:m.reasoning,exercise:m.exercise,criteria:[m.evidence,...(index===4||index===7?[output]:[]),en?'Justify one decision and identify a limitation of your own result.':'Justifica una decisión y señala una limitación de tu propio resultado.'],minutes:35+(index>=4?10:0)}}
  })
}
