import type { ToolPage } from './types'
import { codexPath } from './codex-path'

export type PathLesson = { id: string; title: string; purpose: string; explanation: string[]; example: string; steps: string[]; check: string; errors: string[] }
// Concrete practice briefs. These are teaching exercises, never claims of a completed external run.
const cases: Record<string, [string, string, string, string]> = {
  codex: ['Un formulario de reservas acepta cero huéspedes.', 'A booking form accepts zero guests.', '1 huésped se acepta; 0 muestra un error y no crea la reserva.', '1 guest is accepted; 0 shows an error and creates no booking.'],
  cursor: ['El buscador distingue mayúsculas: Ana encuentra un cliente, ana no.', 'Search is case sensitive: Ana finds a customer, ana does not.', 'Ambas búsquedas devuelven el mismo cliente y la lista vacía sigue funcionando.', 'Both searches return the same customer and empty results still work.'],
  'claude-code': ['Una función suma precios como texto y devuelve 1020 para 10 y 20.', 'A function joins prices as text and returns 1020 for 10 and 20.', 'Devuelve 30; una entrada no numérica produce un error controlado.', 'It returns 30; nonnumeric input produces a controlled error.'],
  github: ['Un repositorio de práctica necesita instrucciones de instalación.', 'A practice repository needs installation instructions.', 'Un README se revisa mediante un pull request y otra persona puede seguirlo.', 'A README is reviewed through a pull request and another person can follow it.'],
  n8n: ['Un registro ficticio tiene id RES-001, huéspedes 2 y estado nuevo.', 'A fictional record has id RES-001, guests 2 and status new.', 'El flujo de prueba valida el registro; repetir RES-001 no genera dos resultados finales.', 'The test workflow validates the record; replaying RES-001 does not create two final results.'],
  make: ['Un formulario de prueba recibe id SOL-001 y servicio limpieza.', 'A test form receives id REQ-001 and service cleaning.', 'Un escenario guarda una solicitud de prueba y conserva su identificador.', 'A scenario saves one test request and preserves its identifier.'],
  zapier: ['Una fila de prueba contiene nombre Ana y estado pendiente.', 'A test row contains name Ana and status pending.', 'El Zap crea un único registro en un destino de prueba, con ambos campos correctos.', 'The Zap creates one record in a test destination with both fields correct.'],
  pipedream: ['Un evento de prueba contiene precio 10 y cantidad 3.', 'A test event contains price 10 and quantity 3.', 'La ejecución devuelve total 30 y rechaza cantidades negativas.', 'The run returns total 30 and rejects negative quantities.'],
  python: ['CSV: producto,cantidad,precio; taza,2,5; libro,1,12.', 'CSV: product,quantity,price; mug,2,5; book,1,12.', 'El script calcula 22 y señala las filas con cantidades inválidas.', 'The script calculates 22 and flags rows with invalid quantities.'],
  node: ['Un programa recibe dos argumentos: 10 y 20.', 'A program receives two arguments: 10 and 20.', 'La terminal muestra 30; sin argumentos explica cómo usarlo.', 'The terminal displays 30; without arguments it explains usage.'],
  typescript: ['Una reserva tiene id de texto y huéspedes de tipo número.', 'A booking has a text id and numeric guests.', 'El compilador detecta asignar texto a huéspedes; la app también valida los datos recibidos.', 'The compiler catches assigning text to guests; the app also validates incoming data.'],
  react: ['Una lista de tres tareas necesita marcar cada tarea terminada.', 'A list of three tasks needs individual completion controls.', 'Marcar una tarea cambia solo esa tarea; funciona con teclado.', 'Checking one task changes only that task; keyboard operation works.'],
  tailwind: ['Una tarjeta muestra un título largo, precio y botón de reserva.', 'A card shows a long title, price and booking button.', 'A 320 y 1440 píxeles el texto no se corta y el botón sigue accesible.', 'At 320 and 1440 pixels text is not clipped and the button remains accessible.'],
  vscode: ['Una carpeta contiene index.html y styles.css.', 'A folder contains index.html and styles.css.', 'Encuentras un selector, cambias un color y revisas solo ese cambio.', 'You find a selector, change one color and review only that change.'],
  docker: ['Una aplicación de prueba debe arrancar en un entorno reproducible.', 'A test application needs a reproducible runtime.', 'El contenedor arranca, responde en el puerto documentado y se puede detener.', 'The container starts, responds on the documented port and can be stopped.'],
  postgres: ['Tabla de prueba reservas: R1 por 20 y R2 por 30.', 'Test bookings table: R1 for 20 and R2 for 30.', 'Una consulta devuelve total 50; insertar R1 de nuevo respeta la regla de unicidad.', 'A query returns total 50; inserting R1 again respects uniqueness.'],
  supabase: ['Dos usuarios de prueba tienen una nota privada cada uno.', 'Two test users each have one private note.', 'Cada usuario lee su nota y recibe denegación al pedir la del otro.', 'Each user reads their own note and is denied access to the other.'],
  vercel: ['Una web de prueba muestra un formulario y una página de confirmación.', 'A test website displays a form and confirmation page.', 'La vista previa carga, enviar datos válidos funciona y la recarga conserva la ruta.', 'The preview loads, valid submission works and reloading preserves the route.'],
  sheets: ['Filas: limpieza 40, limpieza 60, reparación 25.', 'Rows: cleaning 40, cleaning 60, repair 25.', 'El total es 125 y el subtotal de limpieza es 100.', 'The total is 125 and the cleaning subtotal is 100.'],
  airtable: ['Tres solicitudes: dos pendientes y una resuelta.', 'Three requests: two pending and one resolved.', 'Una vista filtrada muestra exactamente las dos pendientes.', 'A filtered view shows exactly the two pending requests.'],
  notion: ['Un proyecto necesita tres tareas con responsable y fecha.', 'A project needs three tasks with owner and date.', 'Puedes filtrar tareas pendientes y abrir cada ficha con su información.', 'You can filter pending tasks and open each record with its details.'],
  obsidian: ['Dos notas: Proyecto reservas y Decisiones técnicas.', 'Two notes: Booking project and Technical decisions.', 'El enlace entre ambas abre la nota correcta y una búsqueda encuentra la decisión.', 'The link opens the correct note and search finds the decision.'],
  gmail: ['Un correo ficticio pide cambiar la reserva R1 del lunes al martes.', 'A fictional email asks to move booking R1 from Monday to Tuesday.', 'Un borrador confirma R1 y la nueva fecha; permanece sin enviar.', 'A draft confirms R1 and the new date; it remains unsent.'],
  slack: ['Un equipo de prueba necesita un resumen de tres incidencias.', 'A test team needs a summary of three incidents.', 'Un borrador distingue incidencia, responsable y siguiente paso, sin publicar.', 'A draft separates incident, owner and next step without posting.'],
  telegram: ['Una notificación de prueba informa que RES-001 falló.', 'A test notification reports that RES-001 failed.', 'El contenido identifica el registro y el error; solo se prueba en un chat autorizado.', 'The content identifies record and error; testing uses only an authorized chat.'],
  whatsapp: ['Una persona pide el horario de una tienda ficticia: 9 a 17.', 'Someone asks for a fictional shop schedule: 9 to 17.', 'El borrador responde 9 a 17 y no inventa aperturas en festivos.', 'The draft answers 9 to 17 and does not invent holiday opening hours.'],
  'wispr-flow': ['Dicta: Reserva de Ana Pérez, dos huéspedes, martes a las 17:30.', 'Dictate: Booking for Ana Perez, two guests, Tuesday at 17:30.', 'El texto conserva nombre, cantidad, día y hora después de revisarlo.', 'The text preserves name, quantity, day and time after review.'],
  notebooklm: ['Dos documentos ficticios dicen apertura a las 9 y cierre a las 17.', 'Two fictional documents state opening at 9 and closing at 17.', 'La respuesta cita el documento que respalda cada horario y no inventa festivos.', 'The answer cites the document supporting each time and does not invent holidays.'],
  perplexity: ['Investiga cómo documentar una política de devoluciones para un caso ficticio.', 'Research how to document a returns policy for a fictional case.', 'Cada afirmación factual tiene una fuente abierta y una fecha; separas dudas de hechos.', 'Each factual claim has an opened source and date; you separate uncertainty from facts.'],
  ollama: ['Una nota ficticia contiene tres tareas y dos fechas.', 'A fictional note contains three tasks and two dates.', 'La respuesta conserva las tres tareas y fechas; compruebas dónde se ejecuta el modelo.', 'The answer preserves three tasks and dates; you verify where the model runs.'],
  langchain: ['Tres fragmentos de prueba describen horarios diferentes por sede.', 'Three test snippets describe different schedules per branch.', 'La respuesta usa el fragmento de la sede correcta y devuelve su referencia.', 'The answer uses the correct branch snippet and returns its reference.'],
  huggingface: ['Compara dos modelos para clasificar tres textos ficticios.', 'Compare two models for classifying three fictional texts.', 'Registras licencia, requisitos y las etiquetas obtenidas con la misma muestra.', 'You record license, requirements and labels from the same sample.'],
  replicate: ['Una muestra pública debe pasar por un modelo seleccionado.', 'A public sample must be processed by a selected model.', 'Conservas versión, parámetros y salida; compruebas el consumo antes de repetir.', 'You preserve version, parameters and output; check usage before repeating.'],
  colab: ['Un notebook calcula la media de 10, 20 y 30.', 'A notebook calculates the mean of 10, 20 and 30.', 'Tras reiniciar y ejecutar en orden devuelve 20 sin depender de variables antiguas.', 'After restarting and running in order it returns 20 without stale variables.'],
}
const textTools = ['openai','anthropic','claude','gemini','copilot']
const siteTools = ['base44','bolt','replit','lovable','v0','framer']
const imageTools = ['canva','figma','midjourney','nano-banana']
const videoTools = ['higgsfield','seedance-2-5','heygen','descript','runway']
for (const id of textTools) cases[id] = ['Nota: Ana prepara presupuesto el martes; Luis revisa el jueves. No hay importe acordado.', 'Note: Ana prepares a quote Tuesday; Luis reviews Thursday. No amount is agreed.', 'Una tabla recoge las dos tareas y fechas; el importe figura como no indicado.', 'A table lists both tasks and dates; amount is marked unspecified.']
for (const id of siteTools) cases[id] = ['Una página de una academia ficticia ofrece un curso y un formulario de interés.', 'A fictional academy page offers a course and interest form.', 'El formulario valida correo y muestra confirmación; el menú funciona en móvil.', 'The form validates email and shows confirmation; mobile navigation works.']
for (const id of imageTools) cases[id] = ['Una academia ficticia necesita una pieza visual cuadrada con espacio para título.', 'A fictional academy needs a square visual with space for a title.', 'La exportación es cuadrada, se abre fuera del editor y mantiene el espacio de texto legible.', 'The export is square, opens outside the editor and keeps readable text space.']
for (const id of videoTools) cases[id] = ['Un vídeo de prueba enseña un escritorio antes y después de ordenarlo.', 'A test video shows a desk before and after organizing it.', 'El archivo reproduce ambas escenas en orden y no corta el final ni el audio.', 'The file plays both scenes in order and does not cut off the ending or audio.']
cases.elevenlabs = ['Texto propio: Bienvenido al curso. Hoy crearás tu primer proyecto.', 'Original text: Welcome to the course. Today you will create your first project.', 'El audio dice ambas frases completas con una voz autorizada y se reproduce fuera del editor.', 'Audio contains both full sentences using an authorized voice and plays outside the editor.']
cases.gamma = ['Tres diapositivas: problema, propuesta y siguiente paso para una academia ficticia.', 'Three slides: problem, proposal and next step for a fictional academy.', 'Las tres partes aparecen en orden y la exportación no corta títulos ni párrafos.', 'All three parts appear in order and export does not clip headings or paragraphs.']

export function toolPath(tool: ToolPage, en: boolean): PathLesson[] {
  if (tool.id === 'codex') return codexPath(en)
  const g = tool.guide
  if (!g) return []
  const tr = (es: string, english: string) => en ? english : es
  const sample = cases[tool.id]
  if (!sample) throw new Error(`Missing practice case: ${tool.id}`)
  const input = sample[en ? 1 : 0], output = sample[en ? 3 : 2]
  const safe = tr('Usa un proyecto de práctica y datos ficticios. Conserva una copia antes de cambiarlo.', 'Use a practice project and fictional data. Keep a copy before changing it.')
  const action = g.first
  const errors = g.errors?.map(parts => parts.join(' — ')) || [tr('Si el resultado no coincide, compara la entrada y el paso donde aparece la primera diferencia. Cambia una sola cosa y repite.', 'If the result differs, compare the input and the first step where it diverges. Change one thing and repeat.')]
  const make = (id: string, title: string, purpose: string, explanation: string[], steps: string[], check: string, example = input): PathLesson => ({ id, title, purpose, explanation, steps, check, example, errors: errors.slice(0, 3) })
  return [
    make('01', tr(`Qué puedes resolver con ${tool.label}`, `What you can solve with ${tool.label}`), tr('Decidir cuándo abrir esta herramienta.', 'Decide when to open this tool.'), [g.plain, ...g.matters], [tr('Lee el caso y localiza la entrada y la salida esperada.', 'Read the case and identify input and expected output.'), tr('Explica qué parte harás aquí y qué parte requiere otra herramienta.', 'Explain which part you will do here and which needs another tool.'), ...g.ignore.map(x => tr('Límite: ', 'Limit: ') + x)], output),
    make('02', tr('Preparar el acceso y el espacio de trabajo', 'Prepare access and workspace'), tr('Llegar al entorno correcto antes de empezar.', 'Reach the correct workspace before starting.'), [g.account.free, g.account.warning || safe], g.account.steps.map(([title, how]) => `${title}: ${how}`), tr('Puedes abrir tu espacio de prueba y reconocer dónde se guardará el trabajo.', 'You can open your test workspace and identify where work will be saved.')),
    make('03', tr('Entender las palabras y controles', 'Understand terms and controls'), tr('Reconocer las piezas que vas a utilizar.', 'Recognize the pieces you will use.'), g.words.map(([word, meaning]) => `${word}: ${meaning}`), [...(g.shortcuts || []).map(([key, use]) => `${key}: ${use}`), tr('Localiza en la herramienta dos de estos conceptos y explica su función en el caso.', 'Locate two of these concepts in the tool and explain their role in the case.')], tr('Puedes distinguir la entrada, el resultado y el control para iniciar o detener el trabajo.', 'You can distinguish input, output and the control for starting or stopping work.')),
    make('04', tr('Preparar una primera prueba pequeña', 'Prepare a small first test'), tr('Definir el resultado antes de ejecutar.', 'Define the result before running.'), [safe, tr('Una prueba útil permite decir qué está bien y qué está mal. Evita valorar solo si el resultado parece convincente.', 'A useful test lets you identify success and failure. Do not judge only whether the result looks convincing.')], [tr('Copia los datos del ejemplo en tu espacio de práctica.', 'Copy the sample data into your practice workspace.'), ...action.slice(0, 1), tr('Compara la preparación con el resultado esperado antes de continuar.', 'Compare preparation with the expected result before continuing.')], output),
    make('05', tr('Crear y revisar el primer resultado', 'Create and review the first result'), tr('Completar una operación de principio a fin.', 'Complete one operation end to end.'), [g.plain, ...(g.daily || []).slice(0, 3)], [...action, tr('Abre el resultado y compáralo punto por punto con la comprobación.', 'Open the result and compare it point by point with the check.')], output),
    make('06', tr('Mejorar el resultado sin perder la versión anterior', 'Improve the result while keeping the previous version'), tr('Aprender qué cambio provoca cada efecto.', 'Learn which change causes each effect.'), [tr('Conserva la primera versión como referencia. Si cambias datos, instrucciones y configuración a la vez, no podrás explicar qué produjo la mejora.', 'Keep the first version as a reference. If you change data, instructions and settings together, you cannot explain what caused the improvement.'), ...g.matters.slice(0, 2)], [tr('Guarda una copia del resultado de la lección 5.', 'Keep a copy of the lesson 5 result.'), tr('Elige un único defecto observable y cambia solo lo necesario para corregirlo.', 'Choose one observable defect and change only what is needed to fix it.'), tr('Repite el mismo caso y compara ambas versiones.', 'Repeat the same case and compare both versions.')], tr('La mejora se ve en una comparación y el criterio original sigue cumpliéndose.', 'The improvement is visible in a comparison and the original criterion still holds.')),
    make('07', tr('Detectar y corregir errores', 'Find and fix errors'), tr('Saber dónde mirar cuando algo falla.', 'Know where to look when something fails.'), errors, [tr('Reproduce el problema en una copia con los mismos datos.', 'Reproduce the problem in a copy with the same data.'), tr('Identifica el mensaje o la primera salida incorrecta usando los errores explicados arriba.', 'Identify the message or first incorrect output using the errors explained above.'), tr('Aplica una corrección y repite el caso original.', 'Apply one correction and repeat the original case.')], tr('Puedes explicar causa, cambio y resultado de la repetición sin depender de una respuesta de la IA.', 'You can explain cause, change and rerun result without relying on an AI answer.')),
    make('08', tr('Comprobar casos difíciles', 'Check difficult cases'), tr('Evitar que una demo oculte fallos.', 'Prevent a demo from hiding failures.'), [tr('Una ejecución correcta no demuestra que todas lo sean. Prueba datos ausentes y repeticiones. Si hay una acción externa, usa exclusivamente el destino de prueba configurado.', 'One successful run does not prove all runs will succeed. Test missing data and repetitions. For external actions, use only the configured test destination.')], [tr('Repite el ejemplo sin un dato obligatorio y observa cómo se comunica el problema.', 'Repeat the example without a required value and observe how the issue is reported.'), tr('Repite exactamente la misma entrada y busca duplicados o cambios inesperados.', 'Replay the exact same input and look for duplicates or unexpected changes.'), tr('Vuelve al caso normal y comprueba que sigue funcionando.', 'Return to the normal case and verify it still works.')], tr('Distingues el caso correcto del incompleto y puedes explicar qué hace una repetición.', 'You distinguish the valid case from the incomplete case and can explain what a replay does.')),
    make('09', tr('Guardar, compartir y recuperar', 'Save, share and recover'), tr('Conservar una entrega que otra persona pueda abrir.', 'Keep a deliverable another person can open.'), [g.account.warning || safe, tr('Compartir una vista, exportar un archivo y publicar para todo el mundo son acciones distintas. Elige solo la necesaria para quien recibe tu trabajo.', 'Sharing a view, exporting a file and publishing publicly are different actions. Choose only what the recipient needs.')], [tr('Guarda una versión identificable y sus datos de entrada.', 'Save an identifiable version and its input data.'), tr('Abre de nuevo el archivo o enlace usando los permisos del destinatario de prueba.', 'Reopen the file or link using the test recipient permissions.'), tr('Comprueba que puedes volver a la versión anterior sin borrar la entrega actual.', 'Verify you can recover the previous version without deleting the current deliverable.')], tr('La entrega abre correctamente y has comprobado su recuperación.', 'The deliverable opens correctly and recovery has been checked.')),
    make('10', tr('Aplicarlo a tu proyecto y medir el resultado', 'Apply it to your project and measure the result'), tr('Pasar del ejercicio a una mejora demostrable.', 'Move from exercise to a demonstrable improvement.'), [tr('Usa el mismo recorrido con un caso permitido de tu proyecto. Compara tiempo y errores con la forma anterior de trabajar. Una estimación inicial sigue siendo una estimación hasta medir casos reales.', 'Use the same process with an authorized case from your project. Compare time and errors with your previous method. An initial estimate remains an estimate until real cases are measured.')], [tr('Define quién necesita el resultado y con qué frecuencia.', 'Define who needs the result and how often.'), tr('Ejecuta el caso normal y las pruebas de la lección 8 en el entorno permitido.', 'Run the normal case and lesson 8 tests in the authorized environment.'), tr('En Mi proyecto, guarda la entrega, sus límites, el tiempo medido y el siguiente paso.', 'In My project, save the deliverable, limitations, measured time and next step.')], tr('Otra persona puede repetir el trabajo con tus instrucciones y puedes mostrar qué ha mejorado.', 'Another person can repeat the work using your instructions and you can show what improved.')),
  ]
}
